(function(){
'use strict';
if(window.__kepFinalActionsLoaded)return;
window.__kepFinalActionsLoaded=true;
const $=id=>document.getElementById(id);
const v=id=>String($(id)?.value||'').trim();
const kep=()=>document.querySelector('input[name="kep"]:checked')?.value||'';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function trips(){try{const x=typeof getSeaServiceTrips==='function'?getSeaServiceTrips():[];return Array.isArray(x)?x:[]}catch(e){return[]}}
function service(list){try{if(typeof calculateTripsService==='function')return calculateTripsService(list||[])}catch(e){}let n=0;(list||[]).forEach(t=>{if(!t?.embark||!t?.discharge)return;let d=new Date(t.embark+'T12:00:00'),e=new Date(t.discharge+'T12:00:00');while(d<=e){n++;d.setDate(d.getDate()+1)}});return{months:Math.floor(n/30),days:n%30,totalDays:n}}
function phrase(s){s=s||{months:0,days:0};return `${s.months} ${s.months===1?'μήνα':'μήνες'} και ${s.days} ${s.days===1?'ημέρα':'ημέρες'}`}
function data(){let k=kep(),t=trips(),s=service(t);return{registry:v('registryNumber'),name:v('fullName'),kep:k?'ΚΕΠ '+k:'',examiner:v(k==='2'?'examinerKep2':'examinerKep1'),docs:v('documentsStatus')||'Δεν έχουν ελεγχθεί',exam:v('examinationStatus')||'Εκκρεμεί',grade:v('examGrade'),decision:v('finalDecision'),result:($('result')?.innerText||'').trim(),trips:t,service:s}}
function report(r){let rows=r.trips.map((t,i)=>{let s=service([t]);return `<tr><td>${i+1}</td><td>${esc(t.embark||'—')}</td><td>${esc(t.discharge||'—')}</td><td>${esc(t.rank||'—')}</td><td>${esc(phrase(s))}</td></tr>`}).join('');return `<div style="width:794px;background:#fff;color:#222;font:13px Arial;padding:34px;box-sizing:border-box"><h1 style="text-align:center;color:#214f83;margin:0">SeaService Calculator</h1><h2 style="text-align:center;color:#214f83">ΑΡΧΕΙΟ ΕΞΕΤΑΣΗΣ ΚΕΠ</h2><h3>ΣΤΟΙΧΕΙΑ ΥΠΟΨΗΦΙΟΥ</h3><table>${row('Μητρώο',r.registry)}${row('Ονοματεπώνυμο',r.name)}${row('ΚΕΠ',r.kep)}${row('Εξεταστής',r.examiner||'—')}</table><h3>ΣΥΝΟΛΙΚΗ ΥΠΗΡΕΣΙΑ</h3><div style="padding:12px;border:2px solid #214f83;text-align:center;font-weight:800;font-size:17px">${esc(phrase(r.service))}</div><h3>ΑΠΟΤΕΛΕΣΜΑ</h3><div style="padding:12px;border:1px solid #ccd3da;white-space:pre-line">${esc(r.result||'—')}</div>${r.trips.length?'<h3>ΤΑΞΙΔΙΑ</h3><table><tr><th>#</th><th>Ναυτολόγηση</th><th>Απόλυση</th><th>Ειδικότητα</th><th>Διάρκεια</th></tr>'+rows+'</table>':''}<h3>ΣΤΟΙΧΕΙΑ ΕΞΕΤΑΣΗΣ</h3><table>${row('Δικαιολογητικά',r.docs)}${row('Εξέταση',r.exam)}${row('Βαθμός',r.grade||'—')}${row('Τελική απόφαση',r.decision||'—')}</table></div>`}
function row(a,b){return `<tr><th style="border:1px solid #ccd3da;padding:7px;background:#f0f3f7;text-align:left">${a}</th><td style="border:1px solid #ccd3da;padding:7px">${esc(b)}</td></tr>`}
async function pdf(){if(typeof html2pdf!=='function')throw Error('PDF library unavailable');let r=data();if(!r.registry||!r.name){alert('Συμπλήρωσε πρώτα Μητρώο και Ονοματεπώνυμο.');return null}let host=document.createElement('div');host.style.cssText='position:fixed;left:-10000px;top:0;z-index:-1';host.innerHTML=report(r);document.body.appendChild(host);try{await new Promise(x=>requestAnimationFrame(()=>requestAnimationFrame(x)));return await html2pdf().set({margin:0,filename:`Arxeio-Eksetasis-KEP-${r.registry}.pdf`,image:{type:'jpeg',quality:.96},html2canvas:{scale:1.5,useCORS:true,backgroundColor:'#fff'},jsPDF:{unit:'mm',format:'a4',orientation:'portrait'},pagebreak:{mode:['css'],avoid:['table','tr']}}).from(host.firstElementChild).outputPdf('blob')}finally{host.remove()}}
function download(blob,r){let u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=`Arxeio-Eksetasis-KEP-${r.registry}.pdf`;document.body.appendChild(a);a.click();setTimeout(()=>{a.remove();URL.revokeObjectURL(u)},60000)}
async function doPdf(){try{let r=data(),b=await pdf();if(b)download(b,r)}catch(e){console.error(e);alert('Δεν μπόρεσε να δημιουργηθεί το PDF. Δοκίμασε ξανά.')}}
async function doEmail(){let r=data();if(!r.registry||!r.name){alert('Συμπλήρωσε πρώτα Μητρώο και Ονοματεπώνυμο.');return}try{let b=await pdf();if(b&&navigator.share&&navigator.canShare){let f=new File([b],`Arxeio-Eksetasis-KEP-${r.registry}.pdf`,{type:'application/pdf'});if(navigator.canShare({files:[f]})){await navigator.share({title:'Αρχείο Εξέτασης ΚΕΠ',text:`Αρχείο εξέτασης ΚΕΠ — ${r.name}`,files:[f]});return}}}catch(e){if(e?.name==='AbortError')return;console.error(e)}let body=`Μητρώο: ${r.registry}\nΟνοματεπώνυμο: ${r.name}\nΚΕΠ: ${r.kep}\nΕξεταστής: ${r.examiner||'—'}\nΣυνολική υπηρεσία: ${phrase(r.service)}\nΔικαιολογητικά: ${r.docs}\nΕξέταση: ${r.exam}\nΒαθμός: ${r.grade||'—'}\nΤελική απόφαση: ${r.decision||'—'}`;location.href='mailto:?subject='+encodeURIComponent('Αρχείο Εξέτασης ΚΕΠ — '+r.registry)+'&body='+encodeURIComponent(body)}
function saveOld(el){return el?.id==='saveArchive'||/καταχώριση\s+στο\s+αρχείο/i.test(el?.innerText||el?.textContent||'')}
function isEmail(el){return el?.id==='emailResult'||/αποστολή\s+με\s+email/i.test(el?.innerText||el?.textContent||'')}
function isPdf(el){return ['pdfResult','downloadPdf','savePdf'].includes(el?.id)||/δημιουργία\s*pdf|\bpdf\b/i.test(el?.innerText||el?.textContent||'')}
function isPrint(el){return el?.id==='printResult'||/εκτύπωση/i.test(el?.innerText||el?.textContent||'')}
function hide(){document.querySelectorAll('button,a').forEach(el=>{if(saveOld(el)&&el.id!=='saveArchiveTop')el.style.display='none'})}
window.addEventListener('click',function(e){let el=e.target?.closest?.('button,a');if(!el)return;if(saveOld(el)){e.preventDefault();e.stopImmediatePropagation();el.style.display='none';return}if(isEmail(el)){e.preventDefault();e.stopImmediatePropagation();doEmail();return}if(isPdf(el)){e.preventDefault();e.stopImmediatePropagation();doPdf();return}if(isPrint(el)){e.preventDefault();e.stopImmediatePropagation();window.print();return}},true);
hide();new MutationObserver(hide).observe(document.body,{childList:true,subtree:true});
})();
