/* SeaService Calculator — archive edit/delete controls */
(function(){
  const KEY='seaServiceArchive';
  const read=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'[]')}catch(e){return[]}};
  const write=a=>localStorage.setItem(KEY,JSON.stringify(a));
  const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[c]));
  const filtered=()=>{const reg=(document.getElementById('registryFilter')?.value||'').trim().toLowerCase();const name=(document.getElementById('nameFilter')?.value||'').trim().toLowerCase();const date=document.getElementById('dateFilter')?.value||'';return read().filter(x=>{const d=x.date||'';const iso=d.match(/^(\d{2})\/(\d{2})\/(\d{4})$/)?`${d.slice(6,10)}-${d.slice(3,5)}-${d.slice(0,2)}`:d;return(!reg||String(x.registryNumber||'').toLowerCase().includes(reg))&&(!name||String(x.fullName||'').toLowerCase().includes(name))&&(!date||iso===date)})};
  function decorate(){const box=document.getElementById('archiveResults');if(!box||!box.classList.contains('archive-list'))return;const data=filtered();box.querySelectorAll('.record-card').forEach((card,i)=>{const r=data[i];if(!r)return;card.dataset.recordId=String(r.id);if(card.querySelector('.record-actions'))return;const a=document.createElement('div');a.className='record-actions';a.innerHTML='<button type="button" class="edit-record" data-id="'+esc(r.id)+'">✏️ Επεξεργασία</button><button type="button" class="delete-record" data-id="'+esc(r.id)+'">🗑️ Διαγραφή</button>';card.appendChild(a)});}
  function modal(record){
    document.getElementById('editModal')?.remove();
    const m=document.createElement('div');m.id='editModal';m.innerHTML=`<div class="edit-backdrop"></div><div class="edit-dialog" role="dialog" aria-modal="true"><div class="edit-head"><strong>Επεξεργασία Εξέτασης ΚΕΠ</strong><button type="button" id="closeEdit">×</button></div><div class="edit-grid">
      <label>Ημερομηνία<input id="eDate" type="text" value="${esc(record.date||'')}"></label><label>Ώρα<input id="eTime" type="text" value="${esc(record.time||'')}"></label>
      <label>Αριθμός Μητρώου<input id="eReg" value="${esc(record.registryNumber||'')}"></label><label>Ονοματεπώνυμο<input id="eName" value="${esc(record.fullName||'')}"></label>
      <label>ΚΕΠ<input id="eKep" value="${esc(record.kep||'')}"></label><label>Υπηρεσία<input id="eService" value="${esc(record.service||'')}"></label>
      <label>Υπηρεσία ΚΕΠ 1<input id="eS1" value="${esc(record.serviceKep1||'')}"></label><label>Υπηρεσία ΚΕΠ 2<input id="eS2" value="${esc(record.serviceKep2||'')}"></label>
      <label>Δικαιολογητικά<select id="eDocs"><option>Δεν έχει ελεγχθεί</option><option>Εντάξει</option><option>Ελλιπή</option></select></label>
      <label>Κατάσταση εξέτασης<select id="eStatus"><option>Δεν εξετάστηκε</option><option>Εξετάστηκε - Επιτυχής</option><option>Εξετάστηκε - Ανεπιτυχής</option></select></label>
      <label>Βαθμός εξέτασης<select id="eGrade"><option>Δεν βαθμολογήθηκε</option><option>Καλώς (5,00–6,49)</option><option>Λίαν Καλώς (6,50–8,49)</option><option>Άριστα (8,50–10,00)</option><option>Ανεπιτυχώς (0–4,99)</option></select></label>
      <label>Τελική απόφαση<select id="eDecision"><option>Σε αναμονή</option><option>Μπορεί να προχωρήσει</option><option>Δεν μπορεί να προχωρήσει</option><option>Δεν εξετάστηκε λόγω ανεπαρκούς υπηρεσίας</option><option>Δεν ολοκληρώθηκε λόγω ελλιπών δικαιολογητικών</option></select></label>
      <label class="edit-full">Αποτέλεσμα / Παρατηρήσεις<textarea id="eResult">${esc(record.result||'')}</textarea></label>
    </div><div class="edit-foot"><button type="button" id="cancelEdit">Ακύρωση</button><button type="button" id="saveEdit">💾 Αποθήκευση αλλαγών</button></div></div>`;
    document.body.appendChild(m);
    ['eDocs','eStatus','eGrade','eDecision'].forEach((id,i)=>{const vals=[record.documents||'',record.examinationStatus||'',record.grade||'',record.finalDecision||''];const el=document.getElementById(id);if(vals[i])el.value=vals[i]});
    const close=()=>m.remove();document.getElementById('closeEdit').onclick=close;document.getElementById('cancelEdit').onclick=close;m.querySelector('.edit-backdrop').onclick=close;
    document.getElementById('saveEdit').onclick=()=>{const a=read(),idx=a.findIndex(x=>String(x.id)===String(record.id));if(idx<0)return;const x=a[idx];Object.assign(x,{date:document.getElementById('eDate').value.trim(),time:document.getElementById('eTime').value.trim(),registryNumber:document.getElementById('eReg').value.trim(),fullName:document.getElementById('eName').value.trim(),kep:document.getElementById('eKep').value.trim(),service:document.getElementById('eService').value.trim(),serviceKep1:document.getElementById('eS1').value.trim(),serviceKep2:document.getElementById('eS2').value.trim(),documents:document.getElementById('eDocs').value,examinationStatus:document.getElementById('eStatus').value,grade:document.getElementById('eGrade').value,finalDecision:document.getElementById('eDecision').value,result:document.getElementById('eResult').value.trim(),success:document.getElementById('eStatus').value==='Εξετάστηκε - Επιτυχής'&&document.getElementById('eDecision').value==='Μπορεί να προχωρήσει'});write(a);close();window.render();setTimeout(decorate,0)};
  }
  function remove(id){const r=read().find(x=>String(x.id)===String(id));if(!r)return;if(!confirm('Να διαγραφεί οριστικά αυτή η εξέταση από το Αρχείο;'))return;write(read().filter(x=>String(x.id)!==String(id)));window.render();setTimeout(decorate,0)}
  function init(){
    const style=document.createElement('style');style.textContent=`.record-actions{display:flex;justify-content:flex-end;gap:8px;margin-top:10px;padding-top:10px;border-top:1px solid #e3e5e8}.record-actions button{border:1px solid #d6dbe1;background:#f7f8fa;border-radius:8px;padding:9px 12px;font:inherit;font-weight:700;cursor:pointer}.record-actions .delete-record{color:#9b1c1c}.edit-backdrop{position:fixed;inset:0;background:rgba(10,20,35,.38);z-index:9998}.edit-dialog{position:fixed;z-index:9999;left:50%;top:50%;transform:translate(-50%,-50%);width:min(760px,calc(100% - 24px));max-height:90vh;overflow:auto;background:#fff;border-radius:14px;box-shadow:0 18px 60px rgba(0,0,0,.25);padding:0}.edit-head{display:flex;justify-content:space-between;align-items:center;padding:15px 17px;border-bottom:1px solid #e5e7eb;font-size:17px}.edit-head button{border:0;background:none;font-size:28px;line-height:1;cursor:pointer;color:#667}.edit-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px;padding:16px}.edit-grid label{font-weight:700;font-size:13px}.edit-grid input,.edit-grid select,.edit-grid textarea{display:block;width:100%;box-sizing:border-box;margin-top:5px;padding:10px;border:1px solid #d7dce2;border-radius:8px;font:inherit;background:#fff}.edit-grid textarea{min-height:110px;resize:vertical}.edit-full{grid-column:1/-1}.edit-foot{display:flex;justify-content:flex-end;gap:8px;padding:14px 16px;border-top:1px solid #e5e7eb}.edit-foot button{padding:10px 14px;border-radius:8px;border:1px solid #d2d7de;font:inherit;font-weight:700;cursor:pointer}.edit-foot #saveEdit{background:#f0f4f8}@media(max-width:700px){.edit-grid{grid-template-columns:1fr}.edit-full{grid-column:auto}.record-actions{justify-content:stretch}.record-actions button{flex:1}.edit-foot{position:sticky;bottom:0;background:#fff}}@media print{.record-actions{display:none!important}}`;document.head.appendChild(style);
    const box=document.getElementById('archiveResults');if(box)new MutationObserver(decorate).observe(box,{childList:true,subtree:true});
    document.addEventListener('click',e=>{const edit=e.target.closest('.edit-record');if(edit){const r=read().find(x=>String(x.id)===String(edit.dataset.id));if(r)modal(r)}const del=e.target.closest('.delete-record');if(del)remove(del.dataset.id)});
    setTimeout(decorate,100);
  }
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
