/* KEP candidate flow — bidirectional registry/name lookup and archive/manual KEP handling */
(function(){
'use strict';
const ARCHIVE_KEY='seaServiceArchive';
const $=id=>document.getElementById(id);
const val=id=>(($(id)?.value)||'').trim();
const read=()=>{try{const a=JSON.parse(localStorage.getItem(ARCHIVE_KEY)||'[]');return Array.isArray(a)?a:[]}catch(e){return[]}};
const norm=s=>String(s||'').trim().replace(/\s+/g,' ').toLocaleLowerCase('el-GR');
const kep=()=>document.querySelector('input[name="kep"]:checked')?.value||'';
const tripsOf=r=>Array.isArray(r?.trips)?r.trips:[];
function service(list){const set=new Set();tripsOf({trips:list}).forEach(t=>{if(!t?.embark||!t?.discharge)return;let d=new Date(t.embark+'T00:00:00'),e=new Date(t.discharge+'T00:00:00');while(d<=e){set.add(d.getTime());d.setDate(d.getDate()+1)}});let days=set.size;return{months:Math.floor(days/30),days:days%30,totalDays:days}}
function recoveredService(rec){if(!rec)return{months:0,days:0,totalDays:0};if(rec.kep1ServiceTotalDays!==undefined)return{months:Number(rec.kep1ServiceMonths)||0,days:Number(rec.kep1ServiceDays)||0,totalDays:Number(rec.kep1ServiceTotalDays)||0};if(rec.serviceMonths!==undefined&&String(rec.kep||'')==='ΚΕΠ 1')return{months:Number(rec.serviceMonths)||0,days:Number(rec.serviceDays)||0,totalDays:(Number(rec.serviceMonths)||0)*30+(Number(rec.serviceDays)||0)};return service(tripsOf(rec))}
function cloneInput(id){const old=$(id);if(!old||old.dataset.candidateFlowClone)return old;const n=old.cloneNode(true);n.dataset.candidateFlowClone='1';old.replaceWith(n);return n}
function ensureStatus(){let s=$('candidateFlowStatus');if(!s){s=document.createElement('div');s.id='candidateFlowStatus';s.style.cssText='margin:10px 0 14px;padding:10px 12px;border-radius:8px;font-weight:700;display:none';const p=$('fullName');if(p)p.parentElement.insertBefore(s,p.nextSibling)}return s}
function ensureManual(){let box=$('manualKep1Service');if(box)return box;box=document.createElement('div');box.id='manualKep1Service';box.style.cssText='display:none;margin:10px 0 15px;padding:12px;border:1px solid #dfe3e8;border-radius:9px;background:#fff';const sec=$('kep2Section');if(sec)sec.parentElement.insertBefore(box,sec);else document.body.insertBefore(box,document.body.firstChild);return box}
function renderServiceBox(recovered,s){const box=ensureManual();const m=Number(s?.months)||0,d=Number(s?.days)||0;if(recovered){box.style.border='2px solid #2e9d50';box.style.background='#effaf1';box.innerHTML='<strong style="color:#176b2c">↩ Υπηρεσία ΚΕΠ 1 — Από ανάκτηση Αρχείου</strong><p style="margin:6px 0 10px;font-size:13px;color:#176b2c">Τα στοιχεία βρέθηκαν αυτόματα από το ιστορικό του υποψηφίου και συμπληρώθηκαν από ανάκτηση.</p><div style="display:flex;gap:10px;flex-wrap:wrap"><label style="margin:0;flex:1;min-width:120px;font-weight:700">Μήνες<input id="manualKep1Months" type="number" value="'+m+'" readonly style="width:100%;box-sizing:border-box;background:#f3f3f3"></label><label style="margin:0;flex:1;min-width:120px;font-weight:700">Ημέρες<input id="manualKep1Days" type="number" value="'+d+'" readonly style="width:100%;box-sizing:border-box;background:#f3f3f3"></label></div>';hiddenService(m,d)}else{box.style.border='1px solid #dfe3e8';box.style.background='#fff';box.innerHTML='<strong>Δεν υπάρχουν στοιχεία για ανάκτηση υπηρεσίας ΚΕΠ 1</strong><p style="margin:6px 0 10px;font-size:13px;color:#666">Δεν βρέθηκε προηγούμενη υπηρεσία στο Αρχείο. Συμπληρώστε εδώ την υπηρεσία του ΚΕΠ 1 για να συνεχίσετε στο ΚΕΠ 2.</p><div style="display:flex;gap:10px;flex-wrap:wrap"><label style="margin:0;flex:1;min-width:120px;font-weight:700">Μήνες<input id="manualKep1Months" type="number" min="0" step="1" value="0" style="width:100%;box-sizing:border-box"></label><label style="margin:0;flex:1;min-width:120px;font-weight:700">Ημέρες<input id="manualKep1Days" type="number" min="0" max="29" step="1" value="0" style="width:100%;box-sizing:border-box"></label></div>';box.querySelector('#manualKep1Months').addEventListener('input',syncManual);box.querySelector('#manualKep1Days').addEventListener('input',syncManual);hiddenService(0,0)}}
function syncManual(){const m=Math.max(0,parseInt(val('manualKep1Months')||'0',10)||0),d=Math.min(29,Math.max(0,parseInt(val('manualKep1Days')||'0',10)||0));const hm=$('kep1Months'),hd=$('kep1Days');hiddenService(m,d);if(hm)hm.value=m;if(hd)hd.value=d}
function hiddenService(m,d){let form=$('tripForm');if(!form)return;['kep1Months','kep1Days'].forEach(id=>{if(!$(id)){const h=document.createElement('input');h.type='hidden';h.id=id;form.appendChild(h)}});$('kep1Months').value=m;$('kep1Days').value=d}
function clearRecoveredState(){hiddenService(0,0);if(typeof window.setSeaServiceTrips==='function')window.setSeaServiceTrips([]);['kep1CurrentService','kep1PreviousService'].forEach(id=>{const e=$(id);if(e)e.style.display='none'});const list=$('tripList');if(list)list.innerHTML='Δεν υπάρχουν ακόμη ταξίδια.';const result=$('result');if(result)result.innerHTML='';['documentsStatus','examinationStatus','examGrade','finalDecision'].forEach(id=>{const e=$(id);if(e)e.selectedIndex=0});const w=$('examWarning');if(w){w.style.display='none';w.textContent=''}}
function matching(){const r=val('registryNumber'),n=norm(val('fullName')),a=read();if(r){const byR=a.filter(x=>String(x.registryNumber||'').trim()===r);if(byR.length)return byR}if(n)return a.filter(x=>norm(x.fullName)===n);return[]}
function latestFor(list,k){const x=list.filter(r=>String(r.kep||'').trim()==='ΚΕΠ '+k);return x.sort((a,b)=>Number(b.id||0)-Number(a.id||0))[0]||null}
function applyRecovered(rec){if(!rec)return;const ts=tripsOf(rec);if(ts.length&&typeof window.setSeaServiceTrips==='function')window.setSeaServiceTrips(ts.map(t=>({...t,_recoveredFromArchive:true})));const s=recoveredService(rec);hiddenService(s.months,s.days);return s}
function paint(found){const status=ensureStatus(),r=latestFor(found,'1'),r2=latestFor(found,'2');document.querySelectorAll('.candidate-kep-recovered').forEach(x=>x.remove());document.querySelectorAll('.candidate-kep-green').forEach(x=>x.classList.remove('candidate-kep-green'));const prev=$('kep1PreviousService');if(!r&&prev)prev.style.display='none';if(!r&&$('kep1CurrentService'))$('kep1CurrentService').style.display='none';if(!found.length){status.style.display='none';renderServiceBox(false,{months:0,days:0});const box=ensureManual();box.style.display=kep()==='2'?'block':'none';return}let msg='✓ Βρέθηκε υποψήφιος στο Αρχείο.';if(r)msg+=' Η υπηρεσία ΚΕΠ 1 είναι διαθέσιμη για ανάκτηση.';if(r2)msg+=' Υπάρχει και προηγούμενη καταχώριση ΚΕΠ 2.';status.textContent=msg;status.style.display='block';if(r){const box=$('kep1Choice');if(box){box.classList.add('candidate-kep-green');const n=document.createElement('div');n.className='candidate-kep-recovered';n.textContent='↩ Ανάκτηση δεδομένων ΚΕΠ 1';n.style.cssText='display:inline-block;margin-left:8px;padding:4px 8px;border-radius:6px;background:#e8f5e9;color:#176b2c;border:1px solid #9ad0a3;font-size:12px;font-weight:700';box.appendChild(n)}}if(r2){const box=$('kep2Choice');if(box){box.classList.add('candidate-kep-green');const n=document.createElement('div');n.className='candidate-kep-recovered';n.textContent='↩ Υπάρχει καταχώριση ΚΕΠ 2';n.style.cssText='display:inline-block;margin-left:8px;padding:4px 8px;border-radius:6px;background:#e8f5e9;color:#176b2c;border:1px solid #9ad0a3;font-size:12px;font-weight:700';box.appendChild(n)}}const box=ensureManual();if(kep()==='2'){const rs=r?recoveredService(r):{months:0,days:0,totalDays:0};renderServiceBox(!!r,rs);box.style.display='block'}else box.style.display='none';if(!r&&kep()==='2'){hiddenService(0,0);const result=$('result');if(result)result.innerHTML=''}}
function refresh(){const found=matching(),r=latestFor(found,'1');if(found.length){const reg=$('registryNumber'),name=$('fullName');if(reg&&reg.value.trim()!==String(found[0].registryNumber||'').trim())reg.value=found[0].registryNumber||'';if(name&&(!name.value.trim()||name.dataset.candidateAuto==='1')){name.value=found[0].fullName||'';name.dataset.candidateAuto='1'}}paint(found);if(r)applyRecovered(r);if(!r&&kep()==='2'){hiddenService(0,0);const result=$('result');if(result)result.innerHTML=''}}
function addNewButton(){if($('newCandidateButton'))return;const b=document.createElement('button');b.type='button';b.id='newCandidateButton';b.textContent='＋ Νέα εξέταση / Καθαρισμός';b.style.cssText='width:100%;margin:12px 0;padding:12px;border:1px solid #cfd5dc;border-radius:9px;background:#f5f7f9;color:#26344f;font:inherit;font-weight:800;cursor:pointer';const name=$('fullName');if(name&&name.parentElement)name.parentElement.insertBefore(b,name.nextSibling);b.addEventListener('click',resetAll)}
function resetAll(){clearRecoveredState();['registryNumber','fullName','embark','discharge'].forEach(id=>{const e=$(id);if(e)e.value=''});document.querySelectorAll('input[name="kep"]').forEach(r=>r.checked=false);['examinerKep1','examinerKep2'].forEach(id=>{const e=$(id);if(e)e.selectedIndex=0});const tripForm=$('tripForm');if(tripForm)tripForm.style.display='none';const box1=$('kep1Examiner'),box2=$('kep2Examiner');if(box1)box1.classList.remove('active');if(box2)box2.classList.remove('active');const status=ensureStatus();status.style.display='none';const manual=ensureManual();manual.style.display='none';manual.innerHTML='';const reg=$('registryNumber');if(reg)reg.dataset.candidateAuto='0';window.scrollTo({top:0,behavior:'smooth'})}
function bind(){const reg=cloneInput('registryNumber'),name=cloneInput('fullName');if(!reg||!name)return;let lastIdentity='';const onIdentityChange=()=>{const key=val('registryNumber')+'|'+norm(val('fullName'));if(key!==lastIdentity){lastIdentity=key;clearRecoveredState()}refresh()};reg.addEventListener('input',onIdentityChange);reg.addEventListener('change',onIdentityChange);reg.addEventListener('blur',onIdentityChange);name.addEventListener('input',()=>{name.dataset.candidateAuto='0';onIdentityChange()});name.addEventListener('change',onIdentityChange);document.querySelectorAll('input[name="kep"]').forEach(x=>{if(x.__candidateFlow)return;x.__candidateFlow=true;x.addEventListener('change',()=>{refresh();if(kep()==='2'){const f=matching(),r=latestFor(f,'1');renderServiceBox(!!r,r?recoveredService(r):{months:0,days:0});ensureManual().style.display='block'}else ensureManual().style.display='none'})})}
function css(){if($('candidate-flow-css'))return;const s=document.createElement('style');s.id='candidate-flow-css';s.textContent='.candidate-kep-green{border:2px solid #2e9d50!important;border-radius:9px!important;padding:4px 7px!important;background:#effaf1!important}.candidate-kep-green input[type="radio"]{accent-color:#2e9d50!important}';document.head.appendChild(s)}
function init(){css();addNewButton();bind();ensureManual();refresh()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
setTimeout(init,250);setTimeout(init,800);
})();
