/* KEP candidate flow — final controller for KEP2 previous-service UI */
(function(){
'use strict';
if(window.__kepCandidateFlowLoaded)return;
window.__kepCandidateFlowLoaded=true;
const ARCHIVE_KEY='seaServiceArchive';
const $=id=>document.getElementById(id);
const value=id=>(($(id)?.value)||'').trim();
const selectedKep=()=>document.querySelector('input[name="kep"]:checked')?.value||'';
const archive=()=>{try{const a=JSON.parse(localStorage.getItem(ARCHIVE_KEY)||'[]');return Array.isArray(a)?a:[]}catch(e){return[]}};
const norm=s=>String(s||'').trim().replace(/\s+/g,' ').toLocaleLowerCase('el-GR');
function recordsForCandidate(){const a=archive(),r=value('registryNumber'),n=norm(value('fullName'));if(r){const x=a.filter(v=>String(v.registryNumber||'').trim()===r);if(x.length)return x}return n?a.filter(v=>norm(v.fullName)===n):[]}
function latestKep1(){return recordsForCandidate().filter(v=>String(v.kep||'').trim()==='ΚΕΠ 1').sort((a,b)=>Number(b.id||0)-Number(a.id||0))[0]||null}
function parseServiceText(text){const s=String(text||'').replace(/\s+/g,' ').trim();let m=s.match(/(\d+)\s*μήνες?\s*(?:και\s*)?(\d+)\s*ημέρες?/i);if(!m)m=s.match(/(\d+)\s*μήνες?/i);if(!m)return null;const months=Number(m[1])||0;const days=Number(m[2])||0;return{months,days,totalDays:months*30+days}}
function recoveredService(rec){if(!rec)return{months:0,days:0,totalDays:0};const stored=Number(rec.kep1ServiceTotalDays);if(Number.isFinite(stored)&&stored>0)return{months:Number(rec.kep1ServiceMonths)||Math.floor(stored/30),days:Number(rec.kep1ServiceDays)||stored%30,totalDays:stored};const calc=rec.calculation;const calcService=calc?.currentService;if(calcService&&Number(calcService.totalDays)>0)return{months:Number(calcService.months)||Math.floor(Number(calcService.totalDays)/30),days:Number(calcService.days)||Number(calcService.totalDays)%30,totalDays:Number(calcService.totalDays)};const total=calc?.totalService;if(total&&Number(total.totalDays)>0)return{months:Number(total.months)||Math.floor(Number(total.totalDays)/30),days:Number(total.days)||Number(total.totalDays)%30,totalDays:Number(total.totalDays)};const direct=Number(rec.serviceMonths)||0,directDays=Number(rec.serviceDays)||0;if(direct||directDays)return{months:direct,days:directDays,totalDays:direct*30+directDays};const current=Number(rec.currentServiceTotalDays)||0;if(current>0)return{months:Number(rec.currentServiceMonths)||Math.floor(current/30),days:Number(rec.currentServiceDays)||current%30,totalDays:current};return parseServiceText(rec.serviceText)||parseServiceText(rec.totalServiceText)||parseServiceText(rec.result)||{months:0,days:0,totalDays:0}}
function hidden(m,d){const form=$('tripForm');if(!form)return;['kep1Months','kep1Days'].forEach(id=>{if(!$(id)){const x=document.createElement('input');x.type='hidden';x.id=id;form.appendChild(x)}});$('kep1Months').value=Math.max(0,Number(m)||0);$('kep1Days').value=Math.min(29,Math.max(0,Number(d)||0))}
function ensureBox(){let box=$('manualKep1Service');if(box)return box;box=document.createElement('div');box.id='manualKep1Service';box.style.cssText='margin:10px 0 15px;padding:12px;border:1px solid #dfe3e8;border-radius:9px;background:#fff;position:relative;z-index:50';const form=$('tripForm');if(form?.parentNode)form.parentNode.insertBefore(box,form);else document.body.appendChild(box);return box}
function syncManual(){if(selectedKep()!=='2')return;const m=Math.max(0,parseInt(value('manualKep1Months')||'0',10)||0),d=Math.min(29,Math.max(0,parseInt(value('manualKep1Days')||'0',10)||0));hidden(m,d);window.structuredCalculationResult=null}
function syncVisibleServiceBeforeCalculation(){if(selectedKep()!=='2')return;const m=value('manualKep1Months'),d=value('manualKep1Days');if(m!==''||d!=='')hidden(m,d);if(typeof window.syncStructuredKep2Inputs==='function')window.syncStructuredKep2Inputs();if(typeof window.calculateService==='function')window.calculateService()}
function hideKep1FailureCard(){if(selectedKep()!=='2')return;const previous=$('kep1PreviousService');if(previous)previous.style.display='none';const status=$('kep1InputStatus');if(status)status.innerHTML=''}
function renderBox(){const box=ensureBox();const warning=$('examWarning');if(selectedKep()!=='2'){box.style.display='none';const previous=$('kep1PreviousService');if(previous)previous.style.display='none';return}if(warning)warning.style.display='none';hideKep1FailureCard();const rec=latestKep1();if(rec){const s=recoveredService(rec);box.style.border='2px solid #2e9d50';box.style.background='#effaf1';box.innerHTML='<strong style="color:#176b2c">↩ Υπηρεσία ΚΕΠ 1 — Από ανάκτηση Αρχείου</strong><p style="margin:6px 0 10px;font-size:13px;color:#176b2c">Η υπηρεσία του ΚΕΠ 1 ανακτήθηκε αυτόματα από το Αρχείο.</p><div style="display:flex;gap:10px;flex-wrap:wrap"><label style="flex:1;min-width:120px;font-weight:700">Μήνες<input id="manualKep1Months" type="number" value="'+s.months+'" readonly style="width:100%;box-sizing:border-box;background:#f3f3f3"></label><label style="flex:1;min-width:120px;font-weight:700">Ημέρες<input id="manualKep1Days" type="number" value="'+s.days+'" readonly style="width:100%;box-sizing:border-box;background:#f3f3f3"></label></div>';hidden(s.months,s.days);box.dataset.mode='recovered'}else{if(box.dataset.mode!=='manual'){box.style.border='1px solid #dfe3e8';box.style.background='#fff';box.innerHTML='<strong>Δεν υπάρχουν στοιχεία για ανάκτηση υπηρεσίας ΚΕΠ 1</strong><p style="margin:6px 0 10px;color:#666">Δεν βρέθηκε προηγούμενη υπηρεσία στο Αρχείο. Συμπληρώστε χειροκίνητα την υπηρεσία του ΚΕΠ 1.</p><div style="display:flex;gap:10px;flex-wrap:wrap"><label style="flex:1;min-width:120px;font-weight:700">Μήνες<input id="manualKep1Months" type="number" min="0" step="1" value="0" style="width:100%;box-sizing:border-box"></label><label style="flex:1;min-width:120px;font-weight:700">Ημέρες<input id="manualKep1Days" type="number" min="0" max="29" step="1" value="0" style="width:100%;box-sizing:border-box"></label></div>';box.querySelector('#manualKep1Months').addEventListener('input',syncManual);box.querySelector('#manualKep1Days').addEventListener('input',syncManual);box.dataset.mode='manual';hidden(0,0)}}box.style.display='block'}
function clearCandidate(){hidden(0,0);try{window.kep1SavedTrips=[]}catch(e){}if(typeof window.setSeaServiceTrips==='function')window.setSeaServiceTrips([]);const result=$('result');if(result)result.innerHTML='';['kep1CurrentService','kep1PreviousService','directManualKep1'].forEach(id=>{const e=$(id);if(e)e.style.display='none'});const w=$('examWarning');if(w){w.style.display='none';w.textContent=''}}
function refresh(){renderBox()}
function reset(){clearCandidate();['registryNumber','fullName','embark','discharge'].forEach(id=>{const e=$(id);if(e)e.value=''});document.querySelectorAll('input[name="kep"]').forEach(x=>x.checked=false);const box=ensureBox();box.style.display='none';box.innerHTML='';box.dataset.mode='';window.scrollTo({top:0,behavior:'smooth'})}
function addReset(){if($('newCandidateButton'))return;const b=document.createElement('button');b.type='button';b.id='newCandidateButton';b.textContent='＋ Νέα εξέταση / Καθαρισμός';b.style.cssText='width:100%;margin:12px 0;padding:12px;border:1px solid #cfd5dc;border-radius:9px;background:#f5f7f9;color:#26344f;font:inherit;font-weight:800;cursor:pointer';const n=$('fullName');if(n?.parentElement)n.parentElement.insertBefore(b,n.nextSibling);b.addEventListener('click',reset)}
function bind(){const reg=$('registryNumber'),name=$('fullName');if(reg&&!reg.__candidateUnified){reg.__candidateUnified=true;const change=()=>{clearCandidate();refresh()};reg.addEventListener('change',change);reg.addEventListener('blur',change);reg.addEventListener('input',change)}if(name&&!name.__candidateUnified){name.__candidateUnified=true;const change=()=>{clearCandidate();refresh()};name.addEventListener('change',change);name.addEventListener('blur',change);name.addEventListener('input',change)}document.querySelectorAll('input[name="kep"]').forEach(r=>{if(r.__candidateUnified)return;r.__candidateUnified=true;r.addEventListener('change',refresh)});const add=$('addTrip');if(add&&!add.__kep2Calc){add.__kep2Calc=true;add.addEventListener('click',()=>setTimeout(syncVisibleServiceBeforeCalculation,0))}const calc=$('calculate');if(calc&&!calc.__kep2Calc){calc.__kep2Calc=true;calc.addEventListener('click',()=>setTimeout(syncVisibleServiceBeforeCalculation,0))}}
function init(){addReset();bind();refresh()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
setInterval(refresh,500);
})();