/* KEP candidate flow — bidirectional registry/name lookup and archive/manual KEP handling */
(function(){
'use strict';
const ARCHIVE_KEY='seaServiceArchive';
const $=id=>document.getElementById(id);
const val=id=>(($(id)?.value)||'').trim();
const read=()=>{try{const a=JSON.parse(localStorage.getItem(ARCHIVE_KEY)||'[]');return Array.isArray(a)?a:[]}catch(e){return[]}};
const norm=s=>String(s||'').trim().replace(/\s+/g,' ').toLocaleLowerCase('el-GR');
const kep=()=>document.querySelector('input[name="kep"]:checked')?.value||'';
const tripsOf=r=>Array.isArray(r?.trips)?r.trips:[];
function service(list){const set=new Set();tripsOf({trips:list}).forEach(t=>{if(!t?.embark||!t?.discharge)return;let d=new Date(t.embark+'T00:00:00'),e=new Date(t.discharge+'T00:00:00');while(d<=e){set.add(d.getTime());d.setDate(d.getDate()+1)}});let days=set.size;return{months:Math.floor(days/30),days:days%30,totalDays:days}}
function cloneInput(id){const old=$(id);if(!old||old.dataset.candidateFlowClone)return old;const n=old.cloneNode(true);n.dataset.candidateFlowClone='1';old.replaceWith(n);return n}
function ensureStatus(){let s=$('candidateFlowStatus');if(!s){s=document.createElement('div');s.id='candidateFlowStatus';s.style.cssText='margin:10px 0 14px;padding:10px 12px;border-radius:8px;font-weight:700;display:none';const p=$('fullName');if(p)p.parentElement.insertBefore(s,p.nextSibling)}return s}
function ensureManual(){let box=$('manualKep1Service');if(box)return box;box=document.createElement('div');box.id='manualKep1Service';box.style.cssText='display:none;margin:10px 0 15px;padding:12px;border:1px solid #dfe3e8;border-radius:9px;background:#fff';box.innerHTML='<strong>Υπηρεσία προηγούμενου ΚΕΠ 1 — χειροκίνητη καταχώριση</strong><p style="margin:6px 0 10px;font-size:13px;color:#666">Δεν βρέθηκε προηγούμενη καταχώριση στο Αρχείο. Συμπληρώστε την υπηρεσία του ΚΕΠ 1 για να συνεχίσετε στο ΚΕΠ 2.</p><div style="display:flex;gap:10px;flex-wrap:wrap"><label style="margin:0;flex:1;min-width:120px;font-weight:700">Μήνες<input id="manualKep1Months" type="number" min="0" step="1" value="0" style="width:100%;box-sizing:border-box"></label><label style="margin:0;flex:1;min-width:120px;font-weight:700">Ημέρες<input id="manualKep1Days" type="number" min="0" max="29" step="1" value="0" style="width:100%;box-sizing:border-box"></label></div>';const sec=$('kep2Section');if(sec)sec.parentElement.insertBefore(box,sec);else document.body.insertBefore(box,document.body.firstChild);return box}
function hiddenService(m,d){let a=$('kep1Months'),b=$('kep1Days'),form=$('tripForm');if(!form)return;[[a,'kep1Months'],[b,'kep1Days']].forEach(x=>{if(!x[0]){const h=document.createElement('input');h.type='hidden';h.id=x[1];form.appendChild(h)}});$('kep1Months').value=m;$('kep1Days').value=d}
function matching(){const r=val('registryNumber'),n=norm(val('fullName')),a=read();if(r){const byR=a.filter(x=>String(x.registryNumber||'').trim()===r);if(byR.length)return byR}if(n)return a.filter(x=>norm(x.fullName)===n);return[]}
function latestFor(list,k){const x=list.filter(r=>String(r.kep||'').trim()==='ΚΕΠ '+k);return x.sort((a,b)=>Number(b.id||0)-Number(a.id||0))[0]||null}
function applyRecovered(rec){if(!rec)return;const ts=tripsOf(rec);if(ts.length&&typeof window.setSeaServiceTrips==='function')window.setSeaServiceTrips(ts.map(t=>({...t,_recoveredFromArchive:true})));const s=service(ts);hiddenService(s.months,s.days)}
function paint(found){const s=ensureStatus(),r=latestFor(found,'1'),r2=latestFor(found,'2');document.querySelectorAll('.candidate-kep-recovered').forEach(x=>x.remove());document.querySelectorAll('.candidate-kep-green').forEach(x=>x.classList.remove('candidate-kep-green'));if(!found.length){s.style.display='none';ensureManual().style.display=kep()==='2'?'block':'none';return}let msg='✓ Βρέθηκε υποψήφιος στο Αρχείο.';if(r)msg+=' Η υπηρεσία ΚΕΠ 1 είναι διαθέσιμη για ανάκτηση.';if(r2)msg+=' Υπάρχει και προηγούμενη καταχώριση ΚΕΠ 2.';s.textContent=msg;s.style.display='block';if(r){const box=$('kep1Choice');if(box){box.classList.add('candidate-kep-green');const n=document.createElement('div');n.className='candidate-kep-recovered';n.textContent='↩ Ανάκτηση δεδομένων ΚΕΠ 1';n.style.cssText='display:inline-block;margin-left:8px;padding:4px 8px;border-radius:6px;background:#e8f5e9;color:#176b2c;border:1px solid #9ad0a3;font-size:12px;font-weight:700';box.appendChild(n)}}if(r2){const box=$('kep2Choice');if(box){box.classList.add('candidate-kep-green');const n=document.createElement('div');n.className='candidate-kep-recovered';n.textContent='↩ Υπάρχει καταχώριση ΚΕΠ 2';n.style.cssText='display:inline-block;margin-left:8px;padding:4px 8px;border-radius:6px;background:#e8f5e9;color:#176b2c;border:1px solid #9ad0a3;font-size:12px;font-weight:700';box.appendChild(n)}}ensureManual().style.display=r?'none':(kep()==='2'?'block':'none')}
function refresh(){const found=matching();const r=latestFor(found,'1');if(found.length){const reg=$('registryNumber'),name=$('fullName');if(reg&&reg.value.trim()!==String(found[0].registryNumber||'').trim())reg.value=found[0].registryNumber||'';if(name&&(!name.value.trim()||reg?.dataset.candidateAuto==='1')){name.value=found[0].fullName||'';name.dataset.candidateAuto='1'}}paint(found);if(kep()==='1'&&r)applyRecovered(r);if(kep()==='2'&&r)applyRecovered(r)}else{paint([])}}
function bind(){const reg=cloneInput('registryNumber'),name=cloneInput('fullName');if(!reg||!name)return;const go=()=>{if(reg.value.trim())name.dataset.candidateAuto='0';refresh()};reg.addEventListener('input',go);reg.addEventListener('change',go);reg.addEventListener('blur',go);name.addEventListener('input',()=>{name.dataset.candidateAuto='0';refresh()});name.addEventListener('change',refresh);document.querySelectorAll('input[name="kep"]').forEach(x=>{if(x.__candidateFlow)return;x.__candidateFlow=true;x.addEventListener('change',()=>{refresh();const r=latestFor(matching(),'1');if(kep()==='2'&&r)applyRecovered(r)})})}
function css(){if($('candidate-flow-css'))return;const s=document.createElement('style');s.id='candidate-flow-css';s.textContent='.candidate-kep-green{border:2px solid #2e9d50!important;border-radius:9px!important;padding:4px 7px!important;background:#effaf1!important}.candidate-kep-green input[type="radio"]{accent-color:#2e9d50!important}';document.head.appendChild(s)}
function init(){css();bind();ensureManual();refresh()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
setTimeout(init,250);setTimeout(init,800);
})();
