/* SeaService Calculator — archive / print / email enhancements */
(function () {
    const ARCHIVE_KEY = "seaServiceArchive";
    function readArchive(){try{return JSON.parse(localStorage.getItem(ARCHIVE_KEY)||"[]")}catch(e){return[]}}
    function saveArchive(records){localStorage.setItem(ARCHIVE_KEY,JSON.stringify(records))}
    function currentKep(){const c=document.querySelector('input[name="kep"]:checked');return c?c.value:""}
    function now(){const d=new Date();return {iso:d.toISOString(),date:d.toLocaleDateString('el-GR',{day:'2-digit',month:'2-digit',year:'numeric'}),time:d.toLocaleTimeString('el-GR',{hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false})}}
    function getName(){const e=document.getElementById("fullName");return e?e.value.trim():""}
    function showNameFromArchive(){const reg=(document.getElementById("registryNumber")?.value||"").trim(),name=document.getElementById("fullName");if(!name||!reg)return;const found=readArchive().find(r=>String(r.registryNumber||"")===reg&&r.fullName);if(found){name.value=found.fullName;name.dataset.fromArchive="true"}}
    function buildRecord(){const result=document.getElementById("result"),reg=(document.getElementById("registryNumber")?.value||"").trim(),name=getName();if(!reg||!name||!result||!result.innerText.trim())return null;const n=now(),text=result.innerText.trim();return {id:Date.now(),timestamp:n.iso,date:n.date,time:n.time,registryNumber:reg,fullName:name,kep:currentKep()?"ΚΕΠ "+currentKep():"",service:"Υπηρεσία θα συμπληρωθεί",documents:"Δεν έχει δηλωθεί",result:text,success:!/δεν μπορεί|απορρί|ανεπαρκ|❌/i.test(text),trips:Array.isArray(window.trips)?window.trips:[]}}
    function archiveCurrent(){const r=buildRecord();if(!r){alert("Συμπλήρωσε Μητρώο, Ονοματεπώνυμο και ολοκλήρωσε πρώτα τον υπολογισμό.");return}const a=readArchive();a.unshift(r);saveArchive(a);alert("Η εξέταση καταχωρήθηκε στο Αρχείο Εξέτασης ΚΕΠ.")}
    function printCurrent(){const r=document.getElementById("result");if(!r||!r.innerText.trim()){alert("Κάνε πρώτα τον Υπολογισμό Υπηρεσίας.");return}window.print()}
    function emailCurrent(){const r=buildRecord();if(!r){alert("Συμπλήρωσε Μητρώο, Ονοματεπώνυμο και ολοκλήρωσε πρώτα τον υπολογισμό.");return}const s=encodeURIComponent("Αρχείο Εξέτασης ΚΕΠ — "+r.fullName+" — "+r.registryNumber),b=encodeURIComponent("Αρχείο Εξέτασης ΚΕΠ\n\nΜητρώο: "+r.registryNumber+"\nΟνοματεπώνυμο: "+r.fullName+"\nΚΕΠ: "+r.kep+"\nΗμερομηνία: "+r.date+"\nΏρα: "+r.time+"\n\n"+r.result);window.location.href="mailto:?subject="+s+"&body="+b}
    function addActions(){if(document.getElementById("archiveActions"))return;const result=document.getElementById("result");if(!result)return;const p=document.createElement("div");p.id="archiveActions";p.style.cssText="display:flex;gap:8px;flex-wrap:wrap;margin-top:15px";p.innerHTML='<button type="button" id="printResult">🖨️ Εκτύπωση / PDF</button><button type="button" id="emailResult">✉️ Αποστολή με email</button><button type="button" id="saveArchive">📁 Αποθήκευση στο Αρχείο</button>';result.parentNode.insertBefore(p,result.nextSibling);document.getElementById("printResult").onclick=printCurrent;document.getElementById("emailResult").onclick=emailCurrent;document.getElementById("saveArchive").onclick=archiveCurrent}
    function init(){addActions();const reg=document.getElementById("registryNumber");if(reg)reg.addEventListener("blur",showNameFromArchive);const calculate=document.getElementById("calculate");if(calculate)calculate.addEventListener("click",()=>setTimeout(addActions,50))}
    if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init);else init();
})();
