/* SeaService Calculator — KEP archive / PDF / email / validation */
(function(){
const ARCHIVE_KEY='seaServiceArchive';
const $=id=>document.getElementById(id);
const read=()=>{try{return JSON.parse(localStorage.getItem(ARCHIVE_KEY)||'[]')}catch(e){return[]}};
const write=a=>localStorage.setItem(ARCHIVE_KEY,JSON.stringify(a));
const val=id=>($(id)?.value||'').trim();
const kep=()=>{const x=document.querySelector('input[name="kep"]:checked');return x?x.value:''};
const now=()=>{const d=new Date();return {iso:d.toISOString(),date:d.toLocaleDateString('el-GR',{day:'2-digit',month:'2-digit',year:'numeric'}),time:d.toLocaleTimeString('el-GR',{hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false})}};
const resultText=()=>($('result')?.innerText||'').trim();
const blocked=t=>/δεν μπορεί να εξεταστεί|μικρότερη από την ελάχιστα απαιτούμενη|ανεπαρκή υπηρεσία/i.test(t||'');
function examiner(){const id=kep()==='1'?'examinerKep1':'examinerKep2';return val(id)}
function hideManualServiceFields(){['serviceKep1','serviceKep2'].forEach(id=>{const e=$(id);if(e&&e.parentElement)e.parentElement.style.display='none'})}
function syncFields(){hideManualServiceFields();const t=resultText();if(!t)return;const b=blocked(t),docs=val('documentsStatus'),s=$('examinationStatus'),g=$('examGrade'),d=$('finalDecision'),w=$('examWarning');if(b){if(s)s.value='Δεν εξετάστηκε';if(g)g.value='Δεν βαθμολογήθηκε';if(d)d.value='Απορριπτέος λόγω ανεπαρκούς υπηρεσίας';if(w){w.style.display='block';w.textContent='Δεν συμπληρώθηκε η απαιτούμενη υπηρεσία. Ο εξεταζόμενος πρέπει να επανέλθει με την κανονική απαιτούμενη υπηρεσία ή τουλάχιστον τρίμηνη υπηρεσία.'}}else if(docs==='Ελλιπή'){if(s)s.value='Δεν εξετάστηκε';if(g)g.value='Δεν βαθμολογήθηκε';if(d)d.value='Δεν ολοκληρώθηκε λόγω ελλιπών δικαιολογητικών';if(w){w.style.display='block';w.textContent='Τα δικαιολογητικά είναι ελλιπή. Η εξέταση δεν ολοκληρώνεται μέχρι να συμπληρωθούν.'}}else{if(w)w.style.display='none';if(s&&s.value==='Δεν εξετάστηκε')s.value='Εξετάστηκε - Επιτυχής';if(d&&(d.value==='Σε αναμονή'||d.value==='Δεν εξετάστηκε λόγω ανεπαρκούς υπηρεσίας'||d.value==='Απορριπτέος λόγω ανεπαρκούς υπηρεσίας'||d.value==='Δεν ολοκληρώθηκε λόγω ελλιπών δικαιολογητικών'))d.value='Μπορεί να προχωρήσει'}}
function buildRecord(){syncFields();const r=val('registryNumber'),n=val('fullName'),t=resultText(),k=kep(),ex=examiner();if(!r||!n||!t)return null;const z=now(),b=blocked(t),docs=b?'Δεν απαιτείται — ανεπαρκής υπηρεσία':(val('documentsStatus')||'Δεν έχει ελεγχθεί'),status=b?'Δεν εξετάστηκε — απορριπτέος λόγω ανεπαρκούς υπηρεσίας':(docs==='Ελλιπή'?'Δεν εξετάστηκε':val('examinationStatus')||'Δεν εξετάστηκε'),grade=b?'Δεν βαθμολογήθηκε':(docs!=='Εντάξει'?'Δεν βαθμολογήθηκε':val('examGrade')||'Δεν βαθμολογήθηκε');let decision=val('finalDecision')||'Σε αναμονή';if(b)decision='Απορριπτέος λόγω ανεπαρκούς υπηρεσίας — απαιτείται επανέλευση με την κανονική απαιτούμενη υπηρεσία ή τουλάχιστον τρίμηνη υπηρεσία';else if(docs==='Ελλιπή')decision='Δεν ολοκληρώθηκε λόγω ελλιπών δικαιολογητικών';return {id:Date.now(),timestamp:z.iso,date:z.date,time:z.time,registryNumber:r,fullName:n,kep:k?'ΚΕΠ '+k:'',examiner:ex||'Δεν απαιτείται',documents:docs,examinationStatus:status,grade:grade,finalDecision:decision,result:t,success:false,trips:Array.isArray(window.trips)?window.trips:[]}}
function requireMandatory(){const r=buildRecord();if(!r){alert('Για να καταχωρηθεί η εξέταση πρέπει να συμπληρωθούν Μητρώο, Ονοματεπώνυμο και να έχει ολοκληρωθεί ο Υπολογισμός Υπηρεσίας.');return null}if(blocked(r.result))return r;if(!examiner()){alert('Πρέπει να επιλέξεις τον εξεταστή του συγκεκριμένου ΚΕΠ πριν από την καταχώριση.');return null}if(!val('documentsStatus')||val('documentsStatus')==='Δεν έχει ελεγχθεί'){alert('Πρέπει να δηλωθεί η κατάσταση των δικαιολογητικών.');return null}return r}
function archiveCurrent(){const r=requireMandatory();if(!r)return;const a=read();a.unshift(r);write(a);alert('Η εξέταση καταχωρήθηκε στο Αρχείο Εξέτασης ΚΕΠ.')}
function ensureLib(src,test){return new Promise((resolve,reject)=>{if(test()){resolve();return}const s=document.createElement('script');s.src=src;s.onload=()=>test()?resolve():reject(new Error('library'));s.onerror=()=>reject(new Error('library'));document.head.appendChild(s)})}
function reportHtml(r){const esc=s=>String(s??'').replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));const row=(a,b)=>`<tr><th>${esc(a)}</th><td>${esc(b||'—')}</td></tr>`;return `<div style="background:#fff;color:#111;width:760px;padding:34px;font-family:Arial,sans-serif;line-height:1.45"><h1 style="text-align:center;margin:0;font-size:25px">SeaService Calculator</h1><h2 style="text-align:center;margin:5px 0 22px;font-size:20px">ΑΡΧΕΙΟ ΕΞΕΤΑΣΗΣ ΚΕΠ</h2><table style="width:100%;border-collapse:collapse;font-size:13px">${row('Αριθμός Μητρώου',r.registryNumber)}${row('Ονοματεπώνυμο',r.fullName)}${row('Ημερομηνία & ώρα καταχώρισης',r.date+' '+r.time)}${row('ΚΕΠ',r.kep)}${row('Εξεταστής',r.examiner)}${row('Δικαιολογητικά',r.documents)}${row('Κατάσταση εξέτασης',r.examinationStatus)}${row('Βαθμός εξέτασης',r.grade)}${row('Τελική απόφαση',r.finalDecision)}</table><div style="margin-top:18px;border:1px solid #bbb;border-radius:8px;padding:13px"><strong>Αποτέλεσμα / Παρατηρήσεις</strong><div style="white-space:pre-wrap;margin-top:8px">${esc(r.result)}</div></div><div style="margin-top:28px;text-align:center;color:#777;font-size:12px">© 2026 SeaService Calculator. All rights reserved.<br>Σχεδιασμός &amp; Ανάπτυξη: <em>Tassos Ballas</em></div></div>`}
async function pdfBlob(r){await ensureLib('https://cdnjs.cloudflare.com/ajax/libs/html2canvas/1.4.1/html2canvas.min.js',()=>!!window.html2canvas);await ensureLib('https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js',()=>!!window.jspdf);const holder=document.createElement('div');holder.style.cssText='position:fixed;left:-10000px;top:0;z-index:-1;background:#fff';holder.innerHTML=reportHtml(r);document.body.appendChild(holder);await new Promise(x=>requestAnimationFrame(()=>requestAnimationFrame(x)));const canvas=await html2canvas(holder,{scale:2,useCORS:true,backgroundColor:'#fff',windowWidth:900});holder.remove();const {jsPDF}=window.jspdf,pdf=new jsPDF({unit:'mm',format:'a4',orientation:'portrait'}),w=194,h=canvas.height*w/canvas.width,pageH=281;let srcY=0;while(srcY<canvas.height){const slice=Math.min(canvas.height-srcY,Math.floor(canvas.width*pageH/w));const pc=document.createElement('canvas');pc.width=canvas.width;pc.height=slice;pc.getContext('2d').drawImage(canvas,0,srcY,canvas.width,slice,0,0,canvas.width,slice);if(srcY)pdf.addPage();pdf.addImage(pc.toDataURL('image/jpeg',.95),'JPEG',8,8,w,slice*w/canvas.width);srcY+=slice}return pdf.output('blob')}
async function makePdf(){const r=requireMandatory();if(!r)return;try{const blob=await pdfBlob(r);const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`Arxeio-Eksetasis-KEP-${r.registryNumber}.pdf`;a.click();setTimeout(()=>URL.revokeObjectURL(url),3000)}catch(e){alert('Δεν ήταν δυνατή η δημιουργία του PDF. Δοκίμασε ξανά αφού φορτώσει πλήρως η σελίδα.')}}
async function emailCurrent(){const r=requireMandatory();if(!r)return;try{const blob=await pdfBlob(r);const file=new File([blob],`Arxeio-Eksetasis-KEP-${r.registryNumber}.pdf`,{type:'application/pdf'});if(navigator.canShare&&navigator.canShare({files:[file]})){await navigator.share({files:[file],title:'Αρχείο Εξέτασης ΚΕΠ',text:'Επισυνάπτεται αρχείο εξέτασης ΚΕΠ.'});return}const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=file.name;a.click();setTimeout(()=>{URL.revokeObjectURL(url);window.location.href='mailto:?subject='+encodeURIComponent('Αρχείο Εξέτασης ΚΕΠ — '+r.fullName)+'&body='+encodeURIComponent('Επισυνάπτεται αρχείο εξέτασης ΚΕΠ.\n\nΜητρώο: '+r.registryNumber+'\nΟνοματεπώνυμο: '+r.fullName)},1000)}catch(e){alert('Δεν ήταν δυνατή η προετοιμασία του email/PDF. Δοκίμασε ξανά.')}}
function addActions(){if($('archiveActions'))return;const result=$('result');if(!result)return;const p=document.createElement('div');p.id='archiveActions';p.style.cssText='display:flex;gap:8px;flex-wrap:wrap;margin-top:15px';p.innerHTML='<button type="button" id="printResult">📄 Δημιουργία PDF</button><button type="button" id="emailResult">✉️ Αποστολή με email</button><button type="button" id="saveArchive">📁 Καταχώριση στο Αρχείο</button>';result.parentNode.insertBefore(p,result.nextSibling);$('printResult').onclick=makePdf;$('emailResult').onclick=emailCurrent;$('saveArchive').onclick=archiveCurrent}
function init(){hideManualServiceFields();addActions();const reg=$('registryNumber');if(reg){const fill=()=>{const found=read().find(x=>String(x.registryNumber||'')===val('registryNumber')&&x.fullName);if(found&&!val('fullName'))$('fullName').value=found.fullName};reg.addEventListener('blur',fill);reg.addEventListener('input',fill)}const c=$('calculate');if(c)c.addEventListener('click',()=>setTimeout(()=>{addActions();syncFields()},250));['documentsStatus','examinationStatus','examGrade','finalDecision'].forEach(id=>$(id)?.addEventListener('change',syncFields));document.querySelectorAll('input[name="kep"]').forEach(x=>x.addEventListener('change',()=>setTimeout(()=>{syncFields();addActions()},100)))}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();