/* KEP examiner management + mandatory visible selection */
(function(){
const ARCHIVE='seaServiceArchive',EXAMINERS='seaServiceExaminers';
const $=id=>document.getElementById(id);const read=k=>{try{return JSON.parse(localStorage.getItem(k)||'[]')}catch(e){return[]}};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const kep=()=>document.querySelector('input[name="kep"]:checked')?.value||'';
function field(){return $(kep()==='2'?'examinerKep2':'examinerKep1')}
function styles(){if($('examinerRequiredStyles'))return;const s=document.createElement('style');s.id='examinerRequiredStyles';s.textContent='.top-examiner-card{background:#f7f9fb;border:1px solid #dfe3e8;border-radius:10px;padding:13px 14px;margin:12px 0 16px}.top-examiner-head{display:flex;align-items:center;justify-content:space-between;gap:10px;margin-bottom:8px;color:#26344f}.top-examiner-title{font-size:17px;font-weight:800}.top-examiner-required{font-size:11px;font-weight:800;color:#9b1c1c;background:#fff0f0;padding:4px 8px;border-radius:999px}.top-examiner-card select{width:100%;min-height:44px;box-sizing:border-box;padding:8px 10px;border:1px solid #b9c1ca;border-radius:8px;background:#fff;font:inherit}.top-examiner-actions{text-align:right;margin-top:8px}.top-examiner-actions a{font-size:12px;font-weight:700;color:#315f9f;text-decoration:none}.top-examiner-warning{display:none;margin-top:7px;padding:7px 9px;border-radius:7px;background:#fff0f0;color:#9b1c1c;font-size:12px;font-weight:700}@media(max-width:700px){.top-examiner-head{align-items:flex-start;flex-direction:column}}';document.head.appendChild(s)}
function ensure(){styles();if($('topExaminerCard')){render();return}const radios=document.querySelectorAll('input[name="kep"]');if(!radios.length)return;const last=radios[radios.length-1].closest('label')||radios[radios.length-1].parentElement;const c=document.createElement('div');c.id='topExaminerCard';c.className='top-examiner-card';c.innerHTML='<div class="top-examiner-head"><div id="topExaminerTitle" class="top-examiner-title">Εξεταστής ΚΕΠ 1</div><div class="top-examiner-required">ΥΠΟΧΡΕΩΤΙΚΟ</div></div><select id="topExaminerSelect"><option value="">— Επιλέξτε εξεταστή —</option></select><div id="topExaminerWarning" class="top-examiner-warning">Ο εξεταστής είναι υποχρεωτικός πριν από την καταχώριση.</div><div class="top-examiner-actions"><a href="examiner.html">⚙️ Διαχείριση εξεταστών</a></div>';last.parentNode.insertBefore(c,last.nextSibling);$('topExaminerSelect').addEventListener('change',sync);render()}
function render(){const c=$('topExaminerCard'),s=$('topExaminerSelect');if(!c||!s)return;const k=kep();c.style.display=k?'block':'none';$('topExaminerTitle').textContent='Εξεταστής ΚΕΠ '+(k||'1');const a=read(EXAMINERS),f=field(),v=f?.value||'';s.innerHTML='<option value="">'+(a.length?'— Επιλέξτε εξεταστή —':'— Δεν υπάρχουν εξεταστές —')+'</option>'+a.map(n=>'<option value="'+esc(n)+'">'+esc(n)+'</option>').join('');if(a.includes(v))s.value=v;sync()}
function sync(){const s=$('topExaminerSelect'),f=field();if(s&&f)f.value=s.value;if($('topExaminerWarning')&&s?.value)$('topExaminerWarning').style.display='none'}
function latest(registry,k){return read(ARCHIVE).filter(r=>String(r.registryNumber||'')===String(registry)&&String(r.kep||'')==='ΚΕΠ '+k).sort((a,b)=>String(b.timestamp||'').localeCompare(String(a.timestamp||'')))[0]||null}
function serviceDays(r){if(!r)return null;if(Array.isArray(r.trips)&&r.trips.length){const days=new Set();r.trips.forEach(t=>{if(!t.embark||!t.discharge)return;let d=new Date(t.embark),e=new Date(t.discharge);while(d<=e){days.add(d.toISOString().slice(0,10));d.setDate(d.getDate()+1)}});const n=days.size;return n?{months:Math.floor(n/30),days:n%30}:null}return null}
function history(){const r=($('registryNumber')?.value||'').trim();if(!r)return;const p=latest(r,'1');if(!p)return;const s=serviceDays(p);let n=$('continuationNotice');if(!n){n=document.createElement('div');n.id='continuationNotice';const t=$('registryNumber');t?.parentNode.insertBefore(n,t.nextSibling)}n.style.cssText='margin:10px 0;padding:11px;border-radius:8px;background:#eef6ff;border:1px solid #c9def5;color:#234a70;font-size:13px';n.innerHTML='<strong>📋 Προηγούμενη καταχώριση:</strong> ΚΕΠ 1 — '+esc(s?`${s.months} μήνες και ${s.days} ημέρες`:'υπηρεσία καταχωρημένη')+'.<br><span style="font-size:12px">Η προηγούμενη υπηρεσία παραμένει καταγεγραμμένη.</span>'}
function validate(e){sync();if(!field()?.value.trim()){e.preventDefault();e.stopImmediatePropagation();$('topExaminerWarning').style.display='block';$('topExaminerSelect').focus();alert('Πρέπει να επιλέξεις τον εξεταστή του ΚΕΠ '+kep()+' πριν από την καταχώριση.');return false}return true}
function init(){ensure();const save=$('saveArchive');if(save&&!save.dataset.examinerRequired){save.dataset.examinerRequired='1';save.addEventListener('click',validate,true)}document.querySelectorAll('input[name="kep"]').forEach(r=>r.addEventListener('change',()=>setTimeout(()=>{ensure();render();history()},30)));$('registryNumber')?.addEventListener('blur',history);$('registryNumber')?.addEventListener('change',history)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();