/* KEP examiner management + previous-service continuation */
(function(){
const ARCHIVE='seaServiceArchive',EXAMINERS='seaServiceExaminers';
const $=id=>document.getElementById(id);const read=k=>{try{return JSON.parse(localStorage.getItem(k)||'[]')}catch(e){return[]}};const write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const kep=()=>{const x=document.querySelector('input[name="kep"]:checked');return x?x.value:''};const reg=()=>($('registryNumber')?.value||'').trim();
function examinerId(){return kep()==='1'?'examinerKep1':'examinerKep2'}function examinerName(){return ($ (examinerId())?.value||'').trim()}
function ensureUI(){const panel=$('examinationPanel');if(!panel||$('examinerKep1'))return;const grid=panel.querySelector('.exam-grid');if(!grid)return;const box=document.createElement('div');box.className='examiner-box';box.innerHTML='<div class="examiner-select-grid"><label>Εξεταστής ΚΕΠ 1<select id="examinerKep1"><option value="">— Επιλέξτε εξεταστή —</option></select></label><label>Εξεταστής ΚΕΠ 2<select id="examinerKep2"><option value="">— Επιλέξτε εξεταστή —</option></select></label></div><button type="button" id="manageExaminers" class="manage-examiners">⚙️ Διαχείριση εξεταστών</button><div id="examinerManager" class="examiner-manager" style="display:none"></div>';grid.insertBefore(box,grid.firstChild);addStyles();renderLists();$('manageExaminers').onclick=()=>{const m=$('examinerManager');m.style.display=m.style.display==='none'?'block':'none';if(m.style.display==='block')renderManager()}}
function addStyles(){if($('examinerStyles'))return;const s=document.createElement('style');s.id='examinerStyles';s.textContent='.examiner-box{grid-column:1/-1;background:#f5f7fa;border:1px solid #dfe3e8;border-radius:10px;padding:14px;margin-bottom:4px}.examiner-select-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.examiner-select-grid label{display:block;font-weight:700}.examiner-select-grid select{width:100%;box-sizing:border-box;margin-top:6px}.manage-examiners{display:block;margin:12px auto 0;padding:8px 14px;border:1px solid #cfd5dc;border-radius:8px;background:#fff;color:#26344f;font:inherit;font-weight:700;cursor:pointer}.examiner-manager{margin-top:10px}.examiner-manager-card{background:#fff;border:1px solid #dfe3e8;border-radius:10px;padding:12px}.examiner-manager-heading{font-weight:800;margin-bottom:8px}.examiner-row{display:flex;align-items:center;justify-content:space-between;gap:8px;padding:8px 0;border-bottom:1px solid #eee}.remove-examiner{width:42px;height:36px;border:1px solid #ddd;border-radius:7px;background:#fff;cursor:pointer}.examiner-add-row{display:grid;grid-template-columns:1fr auto;gap:8px;margin-top:10px}.new-examiner-input{width:100%;min-height:44px;padding:10px 12px;border:1px solid #bbb;border-radius:8px;font:inherit}.add-examiner{padding:9px 14px;border:0;border-radius:8px;background:#2673e8;color:#fff;font:inherit;font-weight:700;white-space:nowrap}.examiner-empty{color:#777}@media(max-width:700px){.examiner-select-grid{grid-template-columns:1fr}.examiner-add-row{grid-template-columns:1fr}.add-examiner{min-height:42px}}';document.head.appendChild(s)}
function renderLists(){const a=read(EXAMINERS),v1=$('examinerKep1')?.value||'',v2=$('examinerKep2')?.value||'';['examinerKep1','examinerKep2'].forEach(id=>{const s=$(id);if(!s)return;s.innerHTML='<option value="">— Επιλέξτε εξεταστή —</option>'+a.map(n=>'<option value="'+esc(n)+'">'+esc(n)+'</option>').join('');const v=id==='examinerKep1'?v1:v2;if(a.includes(v))s.value=v})}
function renderManager(){const m=$('examinerManager');if(!m)return;const a=read(EXAMINERS);m.innerHTML='<div class="examiner-manager-card"><div class="examiner-manager-heading">Λίστα εξεταστών</div><div class="examiner-list">'+(a.length?a.map((n,i)=>'<div class="examiner-row"><span>'+esc(n)+'</span><button type="button" class="remove-examiner" data-x="'+i+'" aria-label="Αφαίρεση εξεταστή">🗑️</button></div>').join(''):'<span class="examiner-empty">Δεν υπάρχουν εξεταστές.</span>')+'</div><div class="examiner-add-row"><input id="newExaminer" class="new-examiner-input" type="text" autocomplete="name" placeholder="Ονοματεπώνυμο εξεταστή"><button type="button" id="addExaminer" class="add-examiner">＋ Προσθήκη</button></div></div>';m.querySelectorAll('[data-x]').forEach(b=>b.onclick=()=>{const a=read(EXAMINERS),i=+b.dataset.x;if(!a[i])return;if(confirm('Να αφαιρεθεί ο εξεταστής «'+a[i]+'» από τη λίστα;')){const removed=a[i];a.splice(i,1);write(EXAMINERS,a);['examinerKep1','examinerKep2'].forEach(id=>{if($(id)?.value===removed)$(id).value=''});renderLists();renderManager()}});$('addExaminer').onclick=()=>{const i=$('newExaminer'),n=i.value.trim();if(!n){alert('Γράψε το ονοματεπώνυμο του εξεταστή.');i.focus();return}const a=read(EXAMINERS);if(!a.some(x=>x.toLowerCase()===n.toLowerCase()))a.push(n);write(EXAMINERS,a);i.value='';renderLists();renderManager();setTimeout(()=>$('newExaminer')?.focus(),0)};$('newExaminer').addEventListener('keydown',e=>{if(e.key==='Enter')$('addExaminer').click()})}
function latest(registry,k){return read(ARCHIVE).filter(r=>String(r.registryNumber||'')===String(registry)&&String(r.kep||'')==='ΚΕΠ '+k).sort((a,b)=>String(b.timestamp||'').localeCompare(String(a.timestamp||'')))[0]||null}
function serviceDays(r){if(!r||!Array.isArray(r.trips)||!r.trips.length)return null;const days=new Set();r.trips.forEach(t=>{if(!t.embark||!t.discharge)return;let d=new Date(t.embark),e=new Date(t.discharge);while(d<=e){days.add(d.toISOString().slice(0,10));d.setDate(d.getDate()+1)}});const total=days.size;return {months:Math.floor(total/30),days:total%30,total}}
function showHistory(){const r=reg(),k=kep();let note=$('continuationNotice');if(!note){note=document.createElement('div');note.id='continuationNotice';note.style.cssText='margin:10px 0;padding:11px;border-radius:8px;background:#eef6ff;border:1px solid #c9def5;color:#234a70;font-size:13px';const target=$('registryNumber');if(target)target.parentNode.insertBefore(note,target.nextSibling)}if(!r||!k){note.style.display='none';return}const prev=latest(r,'1');if(!prev){note.style.display='none';return}const s=serviceDays(prev);note.style.display='block';note.innerHTML='<strong>📋 Προηγούμενη καταχώριση:</strong> ΚΕΠ 1 — '+esc(s?`${s.months} μήνες και ${s.days} ημέρες`:'υπηρεσία καταχωρημένη')+'.<br><span style="font-size:12px">Η προηγούμενη υπηρεσία παραμένει καταγεγραμμένη και χρησιμοποιείται αυτόματα στον υπολογισμό του ΚΕΠ 2.</span>';if(k==='2'&&s&&$('kep1Months')&&$('kep1Days')){$('kep1Months').value=s.months;$('kep1Days').value=s.days}}
function validateBeforeSave(e){if(!examinerName()){e.stopImmediatePropagation();e.preventDefault();alert('Πρέπει να επιλέξεις τον εξεταστή του συγκεκριμένου ΚΕΠ πριν από την καταχώριση.');return false}return true}
function hookSave(){const b=$('saveArchive');if(!b||b.dataset.examinerHook)return;b.dataset.examinerHook='1';b.addEventListener('click',validateBeforeSave,true)}
function init(){ensureUI();hookSave();const r=$('registryNumber');if(r){r.addEventListener('blur',showHistory);r.addEventListener('change',showHistory)}document.querySelectorAll('input[name="kep"]').forEach(x=>x.addEventListener('change',()=>setTimeout(()=>{ensureUI();showHistory();hookSave()},100)));$('calculate')?.addEventListener('click',()=>setTimeout(()=>{ensureUI();showHistory();hookSave()},220))}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();