(function(){
'use strict';
window.__kepNativePrintV2Loaded=true;
const K='seaServiceArchive';
const $=id=>document.getElementById(id);
const v=id=>String($(id)?.value||'').trim();
const kep=()=>document.querySelector('input[name="kep"]:checked')?.value||'';
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function fmtDate(x){if(!x)return'—';const s=String(x);let d=null;if(/^\d{4}-\d{2}-\d{2}$/.test(s)){const[a,b,c]=s.split('-').map(Number);d=new Date(a,b-1,c,12)}else if(/^\d{2}\/\d{2}\/\d{4}$/.test(s)){const[a,b,c]=s.split('/').map(Number);d=new Date(c,b-1,a,12)}else d=new Date(s);return isNaN(d)?s:d.toLocaleDateString('el-GR',{day:'2-digit',month:'2-digit',year:'numeric'})}
function trips(){try{if(typeof getSeaServiceTrips==='function')return getSeaServiceTrips().map(x=>({...x}))}catch(e){}return[]}
function dates(t){let a=[];if(!t?.embark||!t?.discharge)return a;let d=new Date(t.embark+'T12:00:00'),e=new Date(t.discharge+'T12:00:00');while(d<=e){a.push(d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0'));d.setDate(d.getDate()+1)}return a}
function service(list){let set=new Set();(list||[]).forEach(t=>dates(t).forEach(x=>set.add(x)));if(!set.size)return{months:0,days:0,totalDays:0};let g={};[...set].forEach(s=>{let[y,m,d]=s.split('-').map(Number),k=y+'-'+String(m).padStart(2,'0');(g[k]??={y,m,d:[]}).d.push(d)});let months=0,days=0;Object.values(g).forEach(x=>{let last=new Date(x.y,x.m,0).getDate();if(x.d.length===last&&Math.min(...x.d)===1&&Math.max(...x.d)===last)months++;else days+=x.d.length});months+=Math.floor(days/30);days%=30;return{months,days,totalDays:months*30+days}}
function one(t){return service([t])}
function text(s){return s.months+' '+(s.months===1?'μήνα':'μήνες')+' και '+s.days+' '+(s.days===1?'ημέρα':'ημέρες')}
function records(){try{let a=JSON.parse(localStorage.getItem(K)||'[]');return Array.isArray(a)?a:[]}catch(e){return[]}}
function priorAll(){let r=v('registryNumber'),n=v('fullName').replace(/\s+/g,' ').toLocaleLowerCase('el-GR');return records().filter(x=>String(x.registryNumber||'').trim()===r&&(!n||String(x.fullName||'').replace(/\s+/g,' ').toLocaleLowerCase('el-GR')===n)).sort((a,b)=>String(a.timestamp||a.id).localeCompare(String(b.timestamp||b.id)))}
function prior(){return priorAll().filter(x=>String(x.kep||'')==='ΚΕΠ 1').pop()||null}
function pservice(r){if(!r)return null;let n=Number(r.kep1ServiceTotalDays);if(Number.isFinite(n))return{months:Number(r.kep1ServiceMonths)||Math.floor(n/30),days:Number(r.kep1ServiceDays)||n%30,totalDays:n};return r.calculation?.currentService||null}
function current(){let k=kep(),k2=service(trips());if(k==='1')return{k1:k2,k2:null,total:k2};let r=prior(),a=pservice(r),m=Math.max(0,parseInt(v('manualKep1Months')||v('kep1Months')||0)||0),d=Math.min(29,Math.max(0,parseInt(v('manualKep1Days')||v('kep1Days')||0)||0)),k1=a||{months:m,days:d,totalDays:m*30+d},n=Math.min(k1.totalDays,180)+k2.totalDays;return{k1,k2,total:{months:Math.floor(n/30),days:n%30,totalDays:n},record:r,source:a?'archive':'manual'}}
function eligible(){let s=current();return kep()==='1'?s.k1.totalDays>=90:kep()==='2'&&s.total.totalDays>=360}
function panel(){let p=$('examinationPanel');if(!p)return;p.style.display=kep()&&eligible()?'block':'none';let w=$('examWarning');if(w&&!eligible()&&kep()){w.style.display='block';w.textContent=kep()==='1'?'Δεν συμπληρώθηκε η απαιτούμενη υπηρεσία των 3 μηνών. Η εξέταση δεν μπορεί να πραγματοποιηθεί.':'Δεν συμπληρώθηκε η απαιτούμενη συνολική υπηρεσία των 12 μηνών. Η εξέταση δεν μπορεί να πραγματοποιηθεί.'}else if(w)w.style.display='none';renderStoredHistory()}
function rows(list){if(!list?.length)return'<p>Δεν έχουν αποθηκευτεί αναλυτικά ταξίδια.</p>';return'<table><tr><th>#</th><th>Ναυτολόγηση</th><th>Απόλυση</th><th>Ειδικότητα</th><th>Διάρκεια</th></tr>'+list.map((t,i)=>{let s=one(t);return'<tr><td>'+(i+1)+'</td><td>'+esc(fmtDate(t.embark))+'</td><td>'+esc(fmtDate(t.discharge))+'</td><td>'+esc(t.rank||'—')+'</td><td><b>'+esc(text(s))+'</b></td></tr>'}).join('')+'</table>'}
function renderStoredHistory(){let host=$('kep1PreviousService');if(!host)return;let all=priorAll(),k1=all.filter(x=>x.kep==='ΚΕΠ 1'),k2=all.filter(x=>x.kep==='ΚΕΠ 2');if(!all.length){host.style.display='none';return}let html='<h3 style="margin-top:0;">Αποθηκευμένο ιστορικό υπηρεσίας</h3><p style="margin-top:0;">Βρέθηκαν <b>'+all.length+'</b> αποθηκευμένες καταχωρήσεις για το Μητρώο <b>'+esc(v('registryNumber'))+'</b>.</p>';if(k1.length){html+='<h4>ΚΕΠ 1 — προηγούμενες υπηρεσίες</h4>';k1.forEach((r,i)=>{let s=pservice(r)||service(r.trips||[]);html+='<div style="border:1px solid #dfe3e8;border-radius:8px;padding:10px;margin:8px 0;"><b>Καταχώρηση '+(i+1)+'</b> · '+esc(fmtDate(r.date))+' · Σύνολο: <b>'+esc(s?text(s):'—')+'</b>';if((r.trips||[]).length)html+='<div style="margin-top:8px;line-height:1.7;">'+r.trips.map((t,j)=>'<div>'+(j+1)+'. '+esc(fmtDate(t.embark))+' → '+esc(fmtDate(t.discharge))+' — '+esc(text(one(t)))+'</div>').join('')+'</div>';else html+='<div style="margin-top:6px;color:#777;">Δεν έχουν αποθηκευτεί αναλυτικά ταξίδια σε αυτή την καταχώρηση.</div>';html+='</div>'})}if(kep()==='2'&&k2.length){html+='<h4>ΚΕΠ 2 — προηγούμενες καταχωρήσεις</h4>';k2.forEach((r,i)=>{let s=Number.isFinite(Number(r.kep2ServiceTotalDays))?{months:Number(r.kep2ServiceMonths)||Math.floor(Number(r.kep2ServiceTotalDays)/30),days:Number(r.kep2ServiceDays)||Number(r.kep2ServiceTotalDays)%30,totalDays:Number(r.kep2ServiceTotalDays)}:null;html+='<div style="border:1px solid #dfe3e8;border-radius:8px;padding:10px;margin:8px 0;"><b>Καταχώρηση '+(i+1)+'</b> · '+esc(fmtDate(r.date))+' · ΚΕΠ 2: <b>'+esc(s?text(s):'—')+'</b>';if((r.trips||[]).length)html+='<div style="margin-top:8px;line-height:1.7;">'+r.trips.map((t,j)=>'<div>'+(j+1)+'. '+esc(fmtDate(t.embark))+' → '+esc(fmtDate(t.discharge))+' — '+esc(text(one(t)))+'</div>').join('')+'</div>';else html+='<div style="margin-top:6px;color:#777;">Δεν έχουν αποθηκευτεί αναλυτικά ταξίδια.</div>';html+='</div>'})}if(kep()==='2'){let s=current();html+='<div style="margin-top:10px;padding:11px;border:2px solid #214f83;border-radius:9px;"><b>Σύνολο ΚΕΠ 1:</b> '+esc(text(s.k1))+(s.source==='manual'?' <em>(manual)</em>':'')+'<br><b>ΚΕΠ 1 + ΚΕΠ 2:</b> '+esc(text(s.total))+'</div>'}host.innerHTML=html;host.style.display='block'}
function report(){let k=kep(),s=current(),cur=trips(),r=prior(),h='<h2>ΣΤΟΙΧΕΙΑ ΥΠΟΨΗΦΙΟΥ</h2><table><tr><th>Μητρώο</th><td>'+esc(v('registryNumber'))+'</td></tr><tr><th>Ονοματεπώνυμο</th><td>'+esc(v('fullName'))+'</td></tr><tr><th>ΚΕΠ</th><td>ΚΕΠ '+esc(k)+'</td></tr><tr><th>Εξεταστής</th><td>'+esc(v(k==='2'?'examinerKep2':'examinerKep1')||'—')+'</td></tr></table>';if(k==='1')h+='<h2>ΑΝΑΛΥΤΙΚΗ ΥΠΗΡΕΣΙΑ ΚΕΠ 1</h2>'+rows(cur)+'<div class="total">Σύνολο ΚΕΠ 1: <b>'+text(s.k1)+'</b></div>';else{let old=Array.isArray(r?.trips)?r.trips:[];h+='<h2>ΥΠΗΡΕΣΙΑ ΚΕΠ 1 — ΠΡΟΗΓΟΥΜΕΝΗ</h2><p>Πηγή: <b>'+(r?'Αρχείο':'Χειροκίνητη καταχώριση')+'</b></p>'+rows(old)+'<div class="total">Σύνολο ΚΕΠ 1: <b>'+text(s.k1)+'</b></div><h2>ΑΝΑΛΥΤΙΚΗ ΥΠΗΡΕΣΙΑ ΚΕΠ 2</h2>'+rows(cur)+'<div class="total">Σύνολο ΚΕΠ 2: <b>'+text(s.k2)+'</b></div><h2>ΤΕΛΙΚΟ ΣΥΝΟΛΟ</h2><div class="grand">ΚΕΠ 1 + ΚΕΠ 2: <b>'+text(s.total)+'</b></div>}let p=$('examinationPanel');if(p&&p.style.display!=='none')h+='<h2>ΣΤΟΙΧΕΙΑ ΕΞΕΤΑΣΗΣ</h2><table><tr><th>Δικαιολογητικά</th><td>'+esc(v('documentsStatus'))+'</td></tr><tr><th>Κατάσταση</th><td>'+esc(v('examinationStatus'))+'</td></tr><tr><th>Βαθμολογία</th><td>'+esc(v('examGrade'))+'</td></tr><tr><th>Τελική απόφαση</th><td>'+esc(v('finalDecision'))+'</td></tr></table>';return h}
function print(){let w=window.open('about:blank','_blank');if(!w){alert('Επιτρέψτε αναδυόμενα παράθυρα για την εκτύπωση.');return}w.document.write('<!doctype html><html lang="el"><head><meta charset="utf-8"><title>SeaService Calculator — Αναλυτική Εκτύπωση</title><style>@page{margin:10mm}body{font-family:Arial,sans-serif;color:#222;font-size:10pt}main{max-width:190mm;margin:auto}h1{text-align:center;color:#214f83;font-size:18pt}h2{color:#214f83;font-size:10pt;margin-top:7mm;border-bottom:1px solid #ddd;padding-bottom:2mm}table{width:100%;border-collapse:collapse}th,td{border:1px solid #ccd3da;padding:2mm;text-align:left;vertical-align:top}th{background:#f0f3f7}.total{margin-top:3mm;padding:3mm;background:#f5f7fa;border:1px solid #ddd}.grand{margin-top:3mm;padding:5mm;border:2px solid #214f83;text-align:center;font-size:13pt}</style></head><body><main><h1>SeaService Calculator</h1><p style="text-align:center">ΑΝΑΛΥΤΙΚΟ ΑΡΧΕΙΟ ΕΞΕΤΑΣΗΣ ΚΕΠ — '+fmtDate(new Date())+'</p>'+report()+'</main></body></html>');w.document.close();setTimeout(()=>{w.focus();w.print()},700)}
function save(){let k=kep(),s=current(),cur=trips(),r={id:Date.now(),timestamp:new Date().toISOString(),date:new Date().toLocaleDateString('el-GR'),time:new Date().toLocaleTimeString('el-GR'),registryNumber:v('registryNumber'),fullName:v('fullName'),kep:'ΚΕΠ '+k,examiner:v(k==='2'?'examinerKep2':'examinerKep1'),documents:v('documentsStatus'),examinationStatus:v('examinationStatus'),grade:v('examGrade'),finalDecision:v('finalDecision'),result:($('result')?.innerText||'').trim(),trips:cur,kep1ServiceMonths:s.k1.months,kep1ServiceDays:s.k1.days,kep1ServiceTotalDays:s.k1.totalDays,kep1ServiceSource:k==='2'?s.source:'current',kep1ArchiveId:k==='2'?(s.record?.id||null):null,kep2ServiceMonths:k==='2'?s.k2.months:null,kep2ServiceDays:k==='2'?s.k2.days:null,kep2ServiceTotalDays:k==='2'?s.k2.totalDays:null,calculation:{currentService:k==='1'?s.k1:s.k2,totalService:k==='2'?s.total:s.k1}};if(!r.registryNumber||!r.fullName){alert('Συμπληρώστε Μητρώο και Ονοματεπώνυμο.');return}if(!eligible()){r.examiner='Δεν απαιτείται — ανεπαρκής υπηρεσία';r.documents='Δεν απαιτείται — ανεπαρκής υπηρεσία';r.examinationStatus='Δεν εξετάστηκε — ανεπαρκής υπηρεσία';r.grade='Δεν βαθμολογήθηκε';r.finalDecision='Απορριπτέα'}else if(!r.examiner){alert('Επιλέξτε εξεταστή.');return}else if(!r.documents||r.documents==='Δεν έχει ελεγχθεί'){alert('Δηλώστε την κατάσταση των δικαιολογητικών.');return}let a=records();a.unshift(r);localStorage.setItem(K,JSON.stringify(a));alert('Η εξέταση καταχωρήθηκε στο Αρχείο Εξέτασης ΚΕΠ.')}
document.addEventListener('click',e=>{let b=e.target?.closest?.('#saveArchive,#printResult,#pdfResult,#downloadPdf,#savePdf');if(!b)return;e.preventDefault();e.stopImmediatePropagation();b.id==='saveArchive'?save():print()},true);
document.addEventListener('change',()=>setTimeout(panel,0),true);
document.addEventListener('input',e=>{if(e.target?.id==='registryNumber'||e.target?.id==='fullName')setTimeout(panel,0)},true);
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',panel);else panel();
window.__finalSeaServiceRefresh={service,one,print,save};
})();