/* KEP PDF MASTER v2 — uses the approved repository template. */
(function(){
 const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),u=(n,a,b)=>Number(n)===1?a:b,svc=s=>{let m=+s.months||0,d=+s.days||0;return `${m} ${u(m,'μήνας','μήνες')} και ${d} ${u(d,'ημέρα','ημέρες')}`};
 function calc(list){let set=new Set();(Array.isArray(list)?list:[]).forEach(t=>{if(!t?.embark||!t?.discharge)return;let d=new Date(t.embark+'T00:00:00'),e=new Date(t.discharge+'T00:00:00');while(d<=e){set.add(d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0'));d.setDate(d.getDate()+1)}});let n=set.size;return{months:Math.floor(n/30),days:n%30,totalDays:n}}
 function get(){let k=document.querySelector('input[name="kep"]:checked')?.value||'1',d=new Date();return{registry:$('registryNumber')?.value?.trim()||'',name:$('fullName')?.value?.trim()||'',kep:k,examiner:(k==='2'?$('examinerKep2')?.value:$('examinerKep1')?.value)||'',docs:$('documentsStatus')?.value||'Δεν έχει ελεγχθεί',status:$('examinationStatus')?.value||'Δεν εξετάστηκε',grade:$('examGrade')?.value||'Δεν βαθμολογήθηκε',decision:$('finalDecision')?.value||'',now:d.toLocaleDateString('el-GR',{weekday:'long',day:'numeric',month:'numeric',year:'numeric'})+' — '+d.toLocaleTimeString('el-GR',{hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}),trips:Array.isArray(window.trips)?window.trips:[]}}
 function build(r,t){let k1=r.kep==='2'?calc((typeof kep1SavedTrips!=='undefined'&&Array.isArray(kep1SavedTrips))?kep1SavedTrips:[]):calc(r.trips),k2=r.kep==='2'?calc(r.trips):{months:0,days:0,totalDays:0},total=k1;if(r.kep==='2'){let n=Math.min(k1.totalDays,180)+k2.totalDays;total={months:Math.floor(n/30),days:n%30,totalDays:n}}
 let min=r.kep==='2'?360:90,bad=total.totalDays<min,ok=!bad&&r.decision==='Επιτυχής',reason=r.kep==='2'?'Η συνολική υπηρεσία για το ΚΕΠ 2 είναι μικρότερη από την ελάχιστα απαιτούμενη υπηρεσία των 12 μηνών.':`Η υπηρεσία ΚΕΠ 1 είναι μικρότερη από την ελάχιστα απαιτούμενη υπηρεσία των 3 μηνών.`,con=bad?'Το ΚΕΠ δεν μπορεί να εξεταστεί.':ok?'Το ΚΕΠ εξετάστηκε επιτυχώς.':'Το ΚΕΠ δεν ολοκληρώθηκε επιτυχώς.';
 let rows=r.kep==='2'?[['Ημερομηνία & ώρα καταχώρισης',r.now],['Εξεταστής',r.examiner||'—'],['Υπηρεσία ΚΕΠ 1',svc(k1)],['Νέα υπηρεσία ΚΕΠ 2',svc(k2)],['Συνολική υπηρεσία',svc(total)],['Ελάχιστη απαιτούμενη υπηρεσία','12 μήνες'],['Αποτέλεσμα υπολογισμού',bad?reason:'Η απαιτούμενη υπηρεσία έχει συμπληρωθεί.'],['Δικαιολογητικά',bad?'Δεν απαιτείται — ανεπαρκής υπηρεσία':r.docs],['Κατάσταση εξέτασης',bad?'Δεν εξετάστηκε — ανεπαρκής υπηρεσία':r.status],['Βαθμολογία',bad?'Δεν βαθμολογήθηκε':r.grade]]:[['Ημερομηνία & ώρα καταχώρισης',r.now],['Εξεταστής',r.examiner||'—'],['Συνολική υπηρεσία',svc(k1)],['Ελάχιστη απαιτούμενη υπηρεσία','3 μήνες'],['Αποτέλεσμα υπολογισμού',bad?reason:'Η απαιτούμενη υπηρεσία έχει συμπληρωθεί.'],['Δικαιολογητικά',bad?'Δεν απαιτείται — ανεπαρκής υπηρεσία':r.docs],['Κατάσταση εξέτασης',bad?'Δεν εξετάστηκε — ανεπαρκής υπηρεσία':r.status],['Βαθμολογία',bad?'Δεν βαθμολογήθηκε':r.grade]];
 let rankLines='';let seen=new Set();(r.trips||[]).forEach(x=>{let rank=x.rank||'—';if(seen.has(rank))return;seen.add(rank);let s=calc(r.trips.filter(y=>(y.rank||'—')===rank));rankLines+=`<div class="service-line">Υπηρεσία ανά Ειδικότητα: <strong>${esc(rank)}</strong> ${esc(svc(s))}</div>`});
 if(!rankLines)rankLines=`<div class="service-line">Υπηρεσία ανά Ειδικότητα: —</div>`;
 let details=`<div class="service-line total-line"><span class="black-x">✖</span><strong>Συνολική Υπηρεσία ${esc(svc(total))}</strong></div>${rankLines}`;
 let fail=bad?`<div class="failure-line"><span class="failure-x">✖</span><span class="failure-text">${esc(reason)}</span></div>`:'';
 return t.replace('{{REGISTRY}}',esc(r.registry)).replace('{{NAME}}',esc(r.name)).replace('{{KEP}}','ΚΕΠ '+r.kep).replace('{{ROWS}}',rows.map(x=>`<tr><th>${esc(x[0])}</th><td>${x[1]}</td></tr>`).join('')).replace('{{FINAL_CLASS}}',ok?'ok':'').replace('{{FINAL_STATE}}',ok?'ΕΠΙΤΥΧΗΣ':'ΜΗ ΕΠΙΤΥΧΗΣ').replace('{{DETAILS}}',details).replace('{{FAILURE}}',fail).replace('{{CONCLUSION}}',esc(con));}
 async function make(){if(typeof html2pdf==='undefined'){alert('Το εργαλείο PDF δεν έχει φορτώσει ακόμη.');return null}let r=get();if(!r.registry||!r.name){alert('Συμπλήρωσε πρώτα Μητρώο και Ονοματεπώνυμο.');return null}let t=await fetch('pdf-template-v2-master.html?pdfv=3',{cache:'no-store'}).then(x=>x.text()),h=document.createElement('div');h.style.cssText='position:fixed;left:-10000px;top:0;width:794px;background:#fff;overflow:hidden';h.innerHTML=build(r,t);document.body.appendChild(h);let root=h.querySelector('.page');root.style.height='1123px';root.style.minHeight='1123px';root.style.overflow='hidden';await new Promise(x=>requestAnimationFrame(()=>requestAnimationFrame(x)));try{return await html2pdf().set({margin:0,filename:`Arxeio-Eksetasis-KEP-${r.registry}.pdf`,image:{type:'jpeg',quality:.98},html2canvas:{scale:2,useCORS:true,backgroundColor:'#fff',windowWidth:794},jsPDF:{unit:'mm',format:'a4',orientation:'portrait'},pagebreak:{mode:['css'],avoid:['table','tr','.final-box']}}).from(root).outputPdf('blob')}finally{h.remove()}}
 function openBlob(blob){let u=URL.createObjectURL(blob),w=window.open('about:blank','_blank');if(w){w.location.href=u;setTimeout(()=>URL.revokeObjectURL(u),60000);return}let a=document.createElement('a');a.href=u;a.target='_blank';a.rel='noopener';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),60000)}
 function attach(){['printResult','emailResult'].forEach(id=>{let b=$(id);if(!b||b.dataset.masterV2)return;b.dataset.masterV2='1';b.dataset.fixedPdf='1';b.onclick=async()=>{let viewer=null;if(id==='printResult')viewer=window.open('about:blank','_blank');let blob=await make();if(!blob){if(viewer)viewer.close();return}let r=get(),f=new File([blob],`Arxeio-Eksetasis-KEP-${r.registry}.pdf`,{type:'application/pdf'});if(id==='emailResult'&&navigator.canShare?.({files:[f]})){if(viewer)viewer.close();await navigator.share({files:[f],title:'Αρχείο Εξέτασης ΚΕΠ',text:'Επισυνάπτεται αρχείο εξέτασης ΚΕΠ.'});}else if(viewer){let u=URL.createObjectURL(blob);viewer.location.href=u;setTimeout(()=>URL.revokeObjectURL(u),60000);}else{openBlob(blob)}}})}
 new MutationObserver(attach).observe(document.body,{childList:true,subtree:true});attach();
})();
