/* KEP PDF / PRINT MASTER — stable delegated controls. */
(function(){
'use strict';
if(window.__kepPrintFixLoaded)return;window.__kepPrintFixLoaded=true;
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const u=(n,a,b)=>Number(n)===1?a:b;
const svc=s=>{let m=+s.months||0,d=+s.days||0;return `${m} ${u(m,'μήνας','μήνες')} και ${d} ${u(d,'ημέρα','ημέρες')}`};
function calc(list){let set=new Set();(Array.isArray(list)?list:[]).forEach(t=>{if(!t?.embark||!t?.discharge)return;let d=new Date(t.embark+'T00:00:00'),e=new Date(t.discharge+'T00:00:00');while(d<=e){set.add(d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0'));d.setDate(d.getDate()+1)}});let n=set.size;return{months:Math.floor(n/30),days:n%30,totalDays:n}}
function trips(){try{if(typeof window.getSeaServiceTrips==='function'){const x=window.getSeaServiceTrips();if(Array.isArray(x))return x}}catch(e){}try{if(typeof window.trips!=='undefined'&&Array.isArray(window.trips))return window.trips}catch(e){}return[]}
function get(){let k=document.querySelector('input[name="kep"]:checked')?.value||'1',d=new Date(),list=trips();return{registry:$('registryNumber')?.value?.trim()||'',name:$('fullName')?.value?.trim()||'',kep:k,examiner:(k==='2'?$('examinerKep2')?.value:$('examinerKep1')?.value)||'',docs:$('documentsStatus')?.value||'Δεν έχει ελεγχθεί',status:$('examinationStatus')?.value||'Δεν εξετάστηκε',grade:$('examGrade')?.value||'Δεν βαθμολογήθηκε',decision:$('finalDecision')?.value||'',now:d.toLocaleDateString('el-GR',{weekday:'long',day:'numeric',month:'numeric',year:'numeric'})+' — '+d.toLocaleTimeString('el-GR',{hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}),trips:list}}
function getPrior(r){try{if(typeof kep1SavedTrips!=='undefined'&&Array.isArray(kep1SavedTrips)&&kep1SavedTrips.length)return kep1SavedTrips}catch(e){}try{const a=JSON.parse(localStorage.getItem('seaServiceArchive')||'[]');const x=a.filter(r0=>String(r0.registryNumber||'')===String(r.registry||'')&&String(r0.kep||'')==='ΚΕΠ 1').sort((a,b)=>String(b.timestamp||'').localeCompare(String(a.timestamp||'')))[0];return x?.trips||[]}catch(e){return[]}}
function build(r,t){let k1=r.kep==='2'?calc(getPrior(r)):calc(r.trips),k2=r.kep==='2'?calc(r.trips):{months:0,days:0,totalDays:0},total=k1;if(r.kep==='2'){let n=Math.min(k1.totalDays,180)+k2.totalDays;total={months:Math.floor(n/30),days:n%30,totalDays:n}}
let min=r.kep==='2'?360:90,bad=total.totalDays<min,ok=!bad&&/επιτυχής/i.test(r.status||'')&&r.decision!=='Δεν μπορεί να προχωρήσει';
let reason=r.kep==='2'?'Η συνολική υπηρεσία για το ΚΕΠ 2 είναι μικρότερη από την ελάχιστα απαιτούμενη υπηρεσία των 12 μηνών.':`Η υπηρεσία ΚΕΠ 1 είναι μικρότερη από την ελάχιστα απαιτούμενη υπηρεσία των 3 μηνών.`;
let rows=r.kep==='2'?[['Ημερομηνία & ώρα καταχώρισης',r.now],['Εξεταστής',r.examiner||'—'],['Υπηρεσία ΚΕΠ 1',svc(k1)],['Νέα υπηρεσία ΚΕΠ 2',svc(k2)],['Συνολική υπηρεσία',svc(total)],['Ελάχιστη απαιτούμενη υπηρεσία','12 μήνες'],['Αποτέλεσμα υπολογισμού',bad?reason:'Η απαιτούμενη υπηρεσία έχει συμπληρωθεί.'],['Δικαιολογητικά',bad?'Δεν απαιτείται — ανεπαρκής υπηρεσία':r.docs],['Κατάσταση εξέτασης',bad?'Δεν εξετάστηκε — ανεπαρκής υπηρεσία':r.status],['Βαθμολογία',bad?'Δεν βαθμολογήθηκε':r.grade]]:[['Ημερομηνία & ώρα καταχώρισης',r.now],['Εξεταστής',r.examiner||'—'],['Συνολική υπηρεσία',svc(k1)],['Ελάχιστη απαιτούμενη υπηρεσία','3 μήνες'],['Αποτέλεσμα υπολογισμού',bad?reason:'Η απαιτούμενη υπηρεσία έχει συμπληρωθεί.'],['Δικαιολογητικά',bad?'Δεν απαιτείται — ανεπαρκής υπηρεσία':r.docs],['Κατάσταση εξέτασης',bad?'Δεν εξετάστηκε — ανεπαρκής υπηρεσία':r.status],['Βαθμολογία',bad?'Δεν βαθμολογήθηκε':r.grade]];
let rankLines='',seen=new Set();(r.trips||[]).forEach(x=>{let rank=x.rank||'—';if(seen.has(rank))return;seen.add(rank);let s=calc(r.trips.filter(y=>(y.rank||'—')===rank));rankLines+=`<div class="service-line">Υπηρεσία ανά Ειδικότητα: <strong>${esc(rank)}</strong> ${esc(svc(s))}</div>`});if(!rankLines)rankLines='<div class="service-line">Υπηρεσία ανά Ειδικότητα: —</div>';
let details=`<div class="service-line total-line"><span class="black-x">✖</span><strong>Συνολική Υπηρεσία ${esc(svc(total))}</strong></div>${rankLines}`;let fail=bad?`<div class="failure-line"><span class="failure-x">✖</span><span class="failure-text">${esc(reason)}</span></div>`:'';
return t.replace('{{REGISTRY}}',esc(r.registry)).replace('{{NAME}}',esc(r.name)).replace('{{KEP}}','ΚΕΠ '+r.kep).replace('{{ROWS}}',rows.map(x=>`<tr><th>${esc(x[0])}</th><td>${x[1]}</td></tr>`).join('')).replace('{{FINAL_CLASS}}',ok?'ok':'').replace('{{FINAL_STATE}}',ok?'ΕΠΙΤΥΧΗΣ':'ΜΗ ΕΠΙΤΥΧΗΣ').replace('{{DETAILS}}',details).replace('{{FAILURE}}',fail).replace('{{CONCLUSION}}',esc(bad?'Το ΚΕΠ δεν μπορεί να εξεταστεί.':ok?'Το ΚΕΠ εξετάστηκε επιτυχώς.':'Το ΚΕΠ δεν ολοκληρώθηκε επιτυχώς.'));}
async function loadPdfLib(){if(typeof window.html2pdf==='function')return true;return await new Promise(resolve=>{const s=document.createElement('script');s.src='https://cdnjs.cloudflare.com/ajax/libs/html2pdf.js/0.10.1/html2pdf.bundle.min.js';s.onload=()=>resolve(typeof window.html2pdf==='function');s.onerror=()=>resolve(false);document.head.appendChild(s)})}
async function make(){if(!(await loadPdfLib())){alert('Το εργαλείο δημιουργίας PDF δεν φόρτωσε. Μπορείς να χρησιμοποιήσεις την Εκτύπωση και από εκεί «Αποθήκευση ως PDF».');return null}let r=get();if(!r.registry||!r.name){alert('Συμπλήρωσε πρώτα Μητρώο και Ονοματεπώνυμο.');return null}let response=await fetch('pdf-template-v2-master.html?pdfv=4',{cache:'no-store'});if(!response.ok)throw new Error('PDF template '+response.status);let t=await response.text(),h=document.createElement('div');h.style.cssText='position:fixed;left:-10000px;top:0;width:794px;background:#fff;overflow:hidden';h.innerHTML=build(r,t);document.body.appendChild(h);let root=h.querySelector('.page');if(!root){h.remove();throw new Error('PDF template page missing')}root.style.height='1123px';root.style.minHeight='1123px';root.style.overflow='hidden';await new Promise(x=>requestAnimationFrame(()=>requestAnimationFrame(x)));try{return await window.html2pdf().set({margin:0,filename:`Arxeio-Eksetasis-KEP-${r.registry}.pdf`,image:{type:'jpeg',quality:.98},html2canvas:{scale:2,useCORS:true,backgroundColor:'#fff',windowWidth:794},jsPDF:{unit:'mm',format:'a4',orientation:'portrait'},pagebreak:{mode:['css'],avoid:['table','tr','.final-box']}}).from(root).outputPdf('blob')}finally{h.remove()}}
function openBlob(blob){const u=URL.createObjectURL(blob),w=window.open(u,'_blank');if(w){setTimeout(()=>URL.revokeObjectURL(u),60000);return}const a=document.createElement('a');a.href=u;a.target='_blank';a.rel='noopener';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),60000)}
function isPrintButton(el){return el?.id==='printResult'||/εκτύπ|print/i.test((el?.innerText||el?.textContent||''))}
function isPdfButton(el){return ['emailResult','pdfResult','downloadPdf','savePdf'].includes(el?.id)||/pdf/i.test((el?.innerText||el?.textContent||''))}
async function handle(el){if(!el||el.dataset.kepActionBusy==='1')return;el.dataset.kepActionBusy='1';try{if(isPrintButton(el)&&!isPdfButton(el)){window.print();return}if(isPdfButton(el)){const blob=await make();if(blob)openBlob(blob);return}}catch(e){console.error('KEP PDF/print:',e);alert('Δεν μπόρεσε να δημιουργηθεί το PDF. Η Εκτύπωση μπορεί να χρησιμοποιηθεί ως εναλλακτική.')}finally{setTimeout(()=>{delete el.dataset.kepActionBusy},300)}}
document.addEventListener('click',function(e){const el=e.target?.closest?.('button,a');if(!el)return;if(isPrintButton(el)||isPdfButton(el)){e.preventDefault();e.stopPropagation();handle(el)}},true);
})();
