/* KEP PDF / PRINT v3 — loaded with a unique filename to bypass Safari cache. */
(function(){
'use strict';
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const svc=s=>`${Number(s?.months)||0} ${(Number(s?.months)||0)===1?'μήνας':'μήνες'} και ${Number(s?.days)||0} ${(Number(s?.days)||0)===1?'ημέρα':'ημέρες'}`;
function calc(list){let set=new Set();(Array.isArray(list)?list:[]).forEach(t=>{if(!t?.embark||!t?.discharge)return;let d=new Date(t.embark+'T00:00:00'),e=new Date(t.discharge+'T00:00:00');while(d<=e){set.add(d.toISOString().slice(0,10));d.setDate(d.getDate()+1)}});let n=set.size;return{months:Math.floor(n/30),days:n%30,totalDays:n}}
function getTrips(){try{if(typeof window.getSeaServiceTrips==='function')return window.getSeaServiceTrips()||[]}catch(e){}return[]}
function get(){let k=document.querySelector('input[name="kep"]:checked')?.value||'1',d=new Date();return{registry:$('registryNumber')?.value?.trim()||'',name:$('fullName')?.value?.trim()||'',kep:k,examiner:$(k==='2'?'examinerKep2':'examinerKep1')?.value||'',docs:$('documentsStatus')?.value||'Δεν έχει ελεγχθεί',status:$('examinationStatus')?.value||'Δεν εξετάστηκε',grade:$('examGrade')?.value||'Δεν βαθμολογήθηκε',trips:getTrips(),now:d.toLocaleDateString('el-GR')+' — '+d.toLocaleTimeString('el-GR',{hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false})}}
function prior(r){try{if(typeof kep1SavedTrips!=='undefined'&&Array.isArray(kep1SavedTrips)&&kep1SavedTrips.length)return kep1SavedTrips}catch(e){}try{let a=JSON.parse(localStorage.getItem('seaServiceArchive')||'[]');let x=a.filter(q=>String(q.registryNumber||'')===String(r.registry||'')&&String(q.kep||'')==='ΚΕΠ 1').sort((a,b)=>String(b.timestamp||'').localeCompare(String(a.timestamp||'')))[0];return x?.trips||[]}catch(e){return[]}}
function build(r,t){let k1=r.kep==='2'?calc(prior(r)):calc(r.trips),k2=r.kep==='2'?calc(r.trips):{months:0,days:0,totalDays:0},n=r.kep==='2'?Math.min(k1.totalDays,180)+k2.totalDays:k1.totalDays,total={months:Math.floor(n/30),days:n%30,totalDays:n},bad=n<(r.kep==='2'?360:90);let rows=r.kep==='2'?[['Ημερομηνία & ώρα',r.now],['Εξεταστής',r.examiner||'—'],['Υπηρεσία ΚΕΠ 1',svc(k1)],['Νέα υπηρεσία ΚΕΠ 2',svc(k2)],['Συνολική υπηρεσία',svc(total)],['Ελάχιστη απαιτούμενη υπηρεσία','12 μήνες'],['Αποτέλεσμα υπολογισμού',bad?'Δεν συμπληρώθηκε η απαιτούμενη συνολική υπηρεσία των 12 μηνών.':'Η απαιτούμενη υπηρεσία έχει συμπληρωθεί.'],['Δικαιολογητικά',bad?'Δεν απαιτείται — ανεπαρκής υπηρεσία':r.docs],['Κατάσταση εξέτασης',bad?'Δεν εξετάστηκε — ανεπαρκής υπηρεσία':r.status],['Βαθμολογία',bad?'Δεν βαθμολογήθηκε':r.grade]]:[['Ημερομηνία & ώρα',r.now],['Εξεταστής',r.examiner||'—'],['Συνολική υπηρεσία',svc(total)],['Ελάχιστη απαιτούμενη υπηρεσία','3 μήνες'],['Αποτέλεσμα υπολογισμού',bad?'Δεν συμπληρώθηκε η απαιτούμενη υπηρεσία των 3 μηνών.':'Η απαιτούμενη υπηρεσία έχει συμπληρωθεί.'],['Δικαιολογητικά',bad?'Δεν απαιτείται — ανεπαρκής υπηρεσία':r.docs],['Κατάσταση εξέτασης',bad?'Δεν εξετάστηκε — ανεπαρκής υπηρεσία':r.status],['Βαθμολογία',bad?'Δεν βαθμολογήθηκε':r.grade]];let details=`<div><strong>✖ Συνολική Υπηρεσία ${esc(svc(total))}</strong></div>`;return t.replace('{{REGISTRY}}',esc(r.registry)).replace('{{NAME}}',esc(r.name)).replace('{{KEP}}','ΚΕΠ '+r.kep).replace('{{ROWS}}',rows.map(x=>`<tr><th>${esc(x[0])}</th><td>${esc(x[1])}</td></tr>`).join('')).replace('{{FINAL_CLASS}}',bad?'':'ok').replace('{{FINAL_STATE}}',bad?'ΜΗ ΕΠΙΤΥΧΗΣ':'ΕΠΙΤΥΧΗΣ').replace('{{DETAILS}}',details).replace('{{FAILURE}}',bad?`<div class="failure-line"><span class="failure-x">✖</span>${esc('Δεν συμπληρώθηκε η απαιτούμενη υπηρεσία.')}</div>`:'').replace('{{CONCLUSION}}',bad?'Το ΚΕΠ δεν μπορεί να εξεταστεί.':'Το ΚΕΠ μπορεί να εξεταστεί.')}
async function template(){let x=await fetch('pdf-template-v2-master.html?pdfv=5',{cache:'no-store'});if(!x.ok)throw Error('Δεν φορτώθηκε το πρότυπο PDF');return x.text()}
async function makePdf(){if(typeof html2pdf!=='function')throw Error('Δεν φόρτωσε η βιβλιοθήκη PDF');let r=get();if(!r.registry||!r.name)throw Error('Συμπλήρωσε πρώτα Μητρώο και Ονοματεπώνυμο.');let wrap=document.createElement('div');wrap.style.cssText='position:absolute;left:0;top:0;width:794px;background:#fff;z-index:2147483647;pointer-events:none';wrap.innerHTML=build(r,await template());document.body.appendChild(wrap);let root=wrap.querySelector('.page');root.style.width='794px';root.style.height='1123px';root.style.minHeight='1123px';root.style.margin='0';root.style.background='#fff';await new Promise(x=>requestAnimationFrame(()=>requestAnimationFrame(x)));try{return await html2pdf().set({margin:0,filename:`Arxeio-Eksetasis-KEP-${r.registry}.pdf`,image:{type:'jpeg',quality:.98},html2canvas:{scale:1.5,useCORS:true,backgroundColor:'#fff',windowWidth:794,scrollX:0,scrollY:0},jsPDF:{unit:'mm',format:'a4',orientation:'portrait'},pagebreak:{mode:['css'],avoid:['table','tr','.final-box']}}).from(root).outputPdf('blob')}finally{wrap.remove()}}
function attach(){document.querySelectorAll('#printResult,#pdfResult,#downloadPdf,#savePdf,#emailResult').forEach(b=>{if(b.dataset.printV3)return;b.dataset.printV3='1';b.addEventListener('click',async e=>{e.preventDefault();e.stopImmediatePropagation();try{if(b.id==='printResult'){window.print();return}let blob=await makePdf();let u=URL.createObjectURL(blob);window.open(u,'_blank');setTimeout(()=>URL.revokeObjectURL(u),60000)}catch(err){console.error(err);alert(err.message||'Σφάλμα PDF')}} ,true)})}
attach();new MutationObserver(attach).observe(document.body,{childList:true,subtree:true});
})();
